; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; Test that the scope metadata on global_load/store_b128 produces the same
; cache policy bits as corresponding atomic operations.

; RUN: llc -global-isel=0 -mtriple=amdgcn -mcpu=gfx942  < %s | FileCheck -check-prefixes=GFX942-SDAG  %s
; RUN: llc -global-isel=0 -mtriple=amdgcn -mcpu=gfx1012 < %s | FileCheck -check-prefixes=GFX1012-SDAG %s
; RUN: llc -global-isel=0 -mtriple=amdgcn -mcpu=gfx1100 < %s | FileCheck -check-prefixes=GFX1100-SDAG %s
; RUN: llc -global-isel=0 -mtriple=amdgcn -mcpu=gfx1250 < %s | FileCheck -check-prefixes=GFX1250-SDAG %s

; RUN: llc -global-isel=1 -mtriple=amdgcn -mcpu=gfx942  < %s | FileCheck -check-prefixes=GFX942-ISEL  %s
; RUN: llc -global-isel=1 -mtriple=amdgcn -mcpu=gfx1012 < %s | FileCheck -check-prefixes=GFX1012-ISEL %s
; RUN: llc -global-isel=1 -mtriple=amdgcn -mcpu=gfx1100 < %s | FileCheck -check-prefixes=GFX1100-ISEL %s
; RUN: llc -global-isel=1 -mtriple=amdgcn -mcpu=gfx1250 < %s | FileCheck -check-prefixes=GFX1250-ISEL %s

; scope: wavefront
define <4 x i32> @load_wavefront(ptr addrspace(1) %p) {
; GFX942-SDAG-LABEL: load_wavefront:
; GFX942-SDAG:       ; %bb.0:
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-SDAG-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX942-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-SDAG-LABEL: load_wavefront:
; GFX1012-SDAG:       ; %bb.0:
; GFX1012-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-SDAG-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off
; GFX1012-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1012-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-SDAG-LABEL: load_wavefront:
; GFX1100-SDAG:       ; %bb.0:
; GFX1100-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-SDAG-NEXT:    av_global_load_b128 v[0:3], v[0:1], off
; GFX1100-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1100-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-SDAG-LABEL: load_wavefront:
; GFX1250-SDAG:       ; %bb.0:
; GFX1250-SDAG-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-NEXT:    av_global_load_b128 v[0:3], v[0:1], off
; GFX1250-SDAG-NEXT:    s_wait_loadcnt 0x0
; GFX1250-SDAG-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX942-ISEL-LABEL: load_wavefront:
; GFX942-ISEL:       ; %bb.0:
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-ISEL-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX942-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-ISEL-LABEL: load_wavefront:
; GFX1012-ISEL:       ; %bb.0:
; GFX1012-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-ISEL-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off
; GFX1012-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1012-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-ISEL-LABEL: load_wavefront:
; GFX1100-ISEL:       ; %bb.0:
; GFX1100-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-ISEL-NEXT:    av_global_load_b128 v[0:3], v[0:1], off
; GFX1100-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1100-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-ISEL-LABEL: load_wavefront:
; GFX1250-ISEL:       ; %bb.0:
; GFX1250-ISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-ISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-ISEL-NEXT:    av_global_load_b128 v[0:3], v[0:1], off
; GFX1250-ISEL-NEXT:    s_wait_loadcnt 0x0
; GFX1250-ISEL-NEXT:    s_set_pc_i64 s[30:31]
  %v = call <4 x i32> @llvm.amdgcn.av.global.load.b128(ptr addrspace(1) %p, metadata !0)
  ret <4 x i32> %v
}

; scope: workgroup
define <4 x i32> @load_workgroup(ptr addrspace(1) %p) {
; GFX942-SDAG-LABEL: load_workgroup:
; GFX942-SDAG:       ; %bb.0:
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-SDAG-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off sc0
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX942-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-SDAG-LABEL: load_workgroup:
; GFX1012-SDAG:       ; %bb.0:
; GFX1012-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-SDAG-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off glc
; GFX1012-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1012-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-SDAG-LABEL: load_workgroup:
; GFX1100-SDAG:       ; %bb.0:
; GFX1100-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-SDAG-NEXT:    av_global_load_b128 v[0:3], v[0:1], off glc
; GFX1100-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1100-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-SDAG-LABEL: load_workgroup:
; GFX1250-SDAG:       ; %bb.0:
; GFX1250-SDAG-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-NEXT:    av_global_load_b128 v[0:3], v[0:1], off
; GFX1250-SDAG-NEXT:    s_wait_loadcnt 0x0
; GFX1250-SDAG-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX942-ISEL-LABEL: load_workgroup:
; GFX942-ISEL:       ; %bb.0:
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-ISEL-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off sc0
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX942-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-ISEL-LABEL: load_workgroup:
; GFX1012-ISEL:       ; %bb.0:
; GFX1012-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-ISEL-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off glc
; GFX1012-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1012-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-ISEL-LABEL: load_workgroup:
; GFX1100-ISEL:       ; %bb.0:
; GFX1100-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-ISEL-NEXT:    av_global_load_b128 v[0:3], v[0:1], off glc
; GFX1100-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1100-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-ISEL-LABEL: load_workgroup:
; GFX1250-ISEL:       ; %bb.0:
; GFX1250-ISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-ISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-ISEL-NEXT:    av_global_load_b128 v[0:3], v[0:1], off
; GFX1250-ISEL-NEXT:    s_wait_loadcnt 0x0
; GFX1250-ISEL-NEXT:    s_set_pc_i64 s[30:31]
  %v = call <4 x i32> @llvm.amdgcn.av.global.load.b128(ptr addrspace(1) %p, metadata !1)
  ret <4 x i32> %v
}

; scope: agent
define <4 x i32> @load_agent(ptr addrspace(1) %p) {
; GFX942-SDAG-LABEL: load_agent:
; GFX942-SDAG:       ; %bb.0:
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-SDAG-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off sc1
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX942-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-SDAG-LABEL: load_agent:
; GFX1012-SDAG:       ; %bb.0:
; GFX1012-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-SDAG-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off glc dlc
; GFX1012-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1012-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-SDAG-LABEL: load_agent:
; GFX1100-SDAG:       ; %bb.0:
; GFX1100-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-SDAG-NEXT:    av_global_load_b128 v[0:3], v[0:1], off glc
; GFX1100-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1100-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-SDAG-LABEL: load_agent:
; GFX1250-SDAG:       ; %bb.0:
; GFX1250-SDAG-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-NEXT:    av_global_load_b128 v[0:3], v[0:1], off scope:SCOPE_DEV
; GFX1250-SDAG-NEXT:    s_wait_loadcnt 0x0
; GFX1250-SDAG-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX942-ISEL-LABEL: load_agent:
; GFX942-ISEL:       ; %bb.0:
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-ISEL-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off sc1
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX942-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-ISEL-LABEL: load_agent:
; GFX1012-ISEL:       ; %bb.0:
; GFX1012-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-ISEL-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off glc dlc
; GFX1012-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1012-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-ISEL-LABEL: load_agent:
; GFX1100-ISEL:       ; %bb.0:
; GFX1100-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-ISEL-NEXT:    av_global_load_b128 v[0:3], v[0:1], off glc
; GFX1100-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1100-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-ISEL-LABEL: load_agent:
; GFX1250-ISEL:       ; %bb.0:
; GFX1250-ISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-ISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-ISEL-NEXT:    av_global_load_b128 v[0:3], v[0:1], off scope:SCOPE_DEV
; GFX1250-ISEL-NEXT:    s_wait_loadcnt 0x0
; GFX1250-ISEL-NEXT:    s_set_pc_i64 s[30:31]
  %v = call <4 x i32> @llvm.amdgcn.av.global.load.b128(ptr addrspace(1) %p, metadata !2)
  ret <4 x i32> %v
}

; scope: system (empty string = system scope)
define <4 x i32> @load_system(ptr addrspace(1) %p) {
; GFX942-SDAG-LABEL: load_system:
; GFX942-SDAG:       ; %bb.0:
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-SDAG-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off sc0 sc1
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX942-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-SDAG-LABEL: load_system:
; GFX1012-SDAG:       ; %bb.0:
; GFX1012-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-SDAG-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off glc dlc
; GFX1012-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1012-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-SDAG-LABEL: load_system:
; GFX1100-SDAG:       ; %bb.0:
; GFX1100-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-SDAG-NEXT:    av_global_load_b128 v[0:3], v[0:1], off glc
; GFX1100-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1100-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-SDAG-LABEL: load_system:
; GFX1250-SDAG:       ; %bb.0:
; GFX1250-SDAG-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-NEXT:    av_global_load_b128 v[0:3], v[0:1], off scope:SCOPE_SYS
; GFX1250-SDAG-NEXT:    s_wait_loadcnt 0x0
; GFX1250-SDAG-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX942-ISEL-LABEL: load_system:
; GFX942-ISEL:       ; %bb.0:
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-ISEL-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off sc0 sc1
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX942-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-ISEL-LABEL: load_system:
; GFX1012-ISEL:       ; %bb.0:
; GFX1012-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-ISEL-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off glc dlc
; GFX1012-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1012-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-ISEL-LABEL: load_system:
; GFX1100-ISEL:       ; %bb.0:
; GFX1100-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-ISEL-NEXT:    av_global_load_b128 v[0:3], v[0:1], off glc
; GFX1100-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1100-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-ISEL-LABEL: load_system:
; GFX1250-ISEL:       ; %bb.0:
; GFX1250-ISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-ISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-ISEL-NEXT:    av_global_load_b128 v[0:3], v[0:1], off scope:SCOPE_SYS
; GFX1250-ISEL-NEXT:    s_wait_loadcnt 0x0
; GFX1250-ISEL-NEXT:    s_set_pc_i64 s[30:31]
  %v = call <4 x i32> @llvm.amdgcn.av.global.load.b128(ptr addrspace(1) %p, metadata !3)
  ret <4 x i32> %v
}

; scope: singlethread
define <4 x i32> @load_singlethread(ptr addrspace(1) %p) {
; GFX942-SDAG-LABEL: load_singlethread:
; GFX942-SDAG:       ; %bb.0:
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-SDAG-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX942-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-SDAG-LABEL: load_singlethread:
; GFX1012-SDAG:       ; %bb.0:
; GFX1012-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-SDAG-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off
; GFX1012-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1012-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-SDAG-LABEL: load_singlethread:
; GFX1100-SDAG:       ; %bb.0:
; GFX1100-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-SDAG-NEXT:    av_global_load_b128 v[0:3], v[0:1], off
; GFX1100-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1100-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-SDAG-LABEL: load_singlethread:
; GFX1250-SDAG:       ; %bb.0:
; GFX1250-SDAG-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-NEXT:    av_global_load_b128 v[0:3], v[0:1], off
; GFX1250-SDAG-NEXT:    s_wait_loadcnt 0x0
; GFX1250-SDAG-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX942-ISEL-LABEL: load_singlethread:
; GFX942-ISEL:       ; %bb.0:
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-ISEL-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX942-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-ISEL-LABEL: load_singlethread:
; GFX1012-ISEL:       ; %bb.0:
; GFX1012-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-ISEL-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off
; GFX1012-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1012-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-ISEL-LABEL: load_singlethread:
; GFX1100-ISEL:       ; %bb.0:
; GFX1100-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-ISEL-NEXT:    av_global_load_b128 v[0:3], v[0:1], off
; GFX1100-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1100-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-ISEL-LABEL: load_singlethread:
; GFX1250-ISEL:       ; %bb.0:
; GFX1250-ISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-ISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-ISEL-NEXT:    av_global_load_b128 v[0:3], v[0:1], off
; GFX1250-ISEL-NEXT:    s_wait_loadcnt 0x0
; GFX1250-ISEL-NEXT:    s_set_pc_i64 s[30:31]
  %v = call <4 x i32> @llvm.amdgcn.av.global.load.b128(ptr addrspace(1) %p, metadata !4)
  ret <4 x i32> %v
}

; scope: cluster
define <4 x i32> @load_cluster(ptr addrspace(1) %p) {
; GFX942-SDAG-LABEL: load_cluster:
; GFX942-SDAG:       ; %bb.0:
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-SDAG-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off sc1
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX942-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-SDAG-LABEL: load_cluster:
; GFX1012-SDAG:       ; %bb.0:
; GFX1012-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-SDAG-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off glc dlc
; GFX1012-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1012-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-SDAG-LABEL: load_cluster:
; GFX1100-SDAG:       ; %bb.0:
; GFX1100-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-SDAG-NEXT:    av_global_load_b128 v[0:3], v[0:1], off glc
; GFX1100-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1100-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-SDAG-LABEL: load_cluster:
; GFX1250-SDAG:       ; %bb.0:
; GFX1250-SDAG-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-NEXT:    av_global_load_b128 v[0:3], v[0:1], off scope:SCOPE_SE
; GFX1250-SDAG-NEXT:    s_wait_loadcnt 0x0
; GFX1250-SDAG-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX942-ISEL-LABEL: load_cluster:
; GFX942-ISEL:       ; %bb.0:
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-ISEL-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off sc1
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX942-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-ISEL-LABEL: load_cluster:
; GFX1012-ISEL:       ; %bb.0:
; GFX1012-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-ISEL-NEXT:    global_load_dwordx4 v[0:3], v[0:1], off glc dlc
; GFX1012-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1012-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-ISEL-LABEL: load_cluster:
; GFX1100-ISEL:       ; %bb.0:
; GFX1100-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-ISEL-NEXT:    av_global_load_b128 v[0:3], v[0:1], off glc
; GFX1100-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1100-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-ISEL-LABEL: load_cluster:
; GFX1250-ISEL:       ; %bb.0:
; GFX1250-ISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-ISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-ISEL-NEXT:    av_global_load_b128 v[0:3], v[0:1], off scope:SCOPE_SE
; GFX1250-ISEL-NEXT:    s_wait_loadcnt 0x0
; GFX1250-ISEL-NEXT:    s_set_pc_i64 s[30:31]
  %v = call <4 x i32> @llvm.amdgcn.av.global.load.b128(ptr addrspace(1) %p, metadata !5)
  ret <4 x i32> %v
}

; scope: wavefront
define void @store_wavefront(ptr addrspace(1) %p, <4 x i32> %v) {
; GFX942-SDAG-LABEL: store_wavefront:
; GFX942-SDAG:       ; %bb.0:
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-SDAG-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX942-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-SDAG-LABEL: store_wavefront:
; GFX1012-SDAG:       ; %bb.0:
; GFX1012-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-SDAG-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off
; GFX1012-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-SDAG-LABEL: store_wavefront:
; GFX1100-SDAG:       ; %bb.0:
; GFX1100-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-SDAG-NEXT:    av_global_store_b128 v[0:1], v[2:5], off
; GFX1100-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-SDAG-LABEL: store_wavefront:
; GFX1250-SDAG:       ; %bb.0:
; GFX1250-SDAG-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-NEXT:    av_global_store_b128 v[0:1], v[2:5], off
; GFX1250-SDAG-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX942-ISEL-LABEL: store_wavefront:
; GFX942-ISEL:       ; %bb.0:
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-ISEL-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX942-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-ISEL-LABEL: store_wavefront:
; GFX1012-ISEL:       ; %bb.0:
; GFX1012-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-ISEL-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off
; GFX1012-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-ISEL-LABEL: store_wavefront:
; GFX1100-ISEL:       ; %bb.0:
; GFX1100-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-ISEL-NEXT:    av_global_store_b128 v[0:1], v[2:5], off
; GFX1100-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-ISEL-LABEL: store_wavefront:
; GFX1250-ISEL:       ; %bb.0:
; GFX1250-ISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-ISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-ISEL-NEXT:    av_global_store_b128 v[0:1], v[2:5], off
; GFX1250-ISEL-NEXT:    s_set_pc_i64 s[30:31]
  call void @llvm.amdgcn.av.global.store.b128(ptr addrspace(1) %p, <4 x i32> %v, metadata !0)
  ret void
}

; scope: workgroup
define void @store_workgroup(ptr addrspace(1) %p, <4 x i32> %v) {
; GFX942-SDAG-LABEL: store_workgroup:
; GFX942-SDAG:       ; %bb.0:
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-SDAG-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off sc0
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX942-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-SDAG-LABEL: store_workgroup:
; GFX1012-SDAG:       ; %bb.0:
; GFX1012-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-SDAG-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off
; GFX1012-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-SDAG-LABEL: store_workgroup:
; GFX1100-SDAG:       ; %bb.0:
; GFX1100-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-SDAG-NEXT:    av_global_store_b128 v[0:1], v[2:5], off
; GFX1100-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-SDAG-LABEL: store_workgroup:
; GFX1250-SDAG:       ; %bb.0:
; GFX1250-SDAG-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-NEXT:    av_global_store_b128 v[0:1], v[2:5], off
; GFX1250-SDAG-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX942-ISEL-LABEL: store_workgroup:
; GFX942-ISEL:       ; %bb.0:
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-ISEL-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off sc0
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX942-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-ISEL-LABEL: store_workgroup:
; GFX1012-ISEL:       ; %bb.0:
; GFX1012-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-ISEL-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off
; GFX1012-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-ISEL-LABEL: store_workgroup:
; GFX1100-ISEL:       ; %bb.0:
; GFX1100-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-ISEL-NEXT:    av_global_store_b128 v[0:1], v[2:5], off
; GFX1100-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-ISEL-LABEL: store_workgroup:
; GFX1250-ISEL:       ; %bb.0:
; GFX1250-ISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-ISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-ISEL-NEXT:    av_global_store_b128 v[0:1], v[2:5], off
; GFX1250-ISEL-NEXT:    s_set_pc_i64 s[30:31]
  call void @llvm.amdgcn.av.global.store.b128(ptr addrspace(1) %p, <4 x i32> %v, metadata !1)
  ret void
}

; scope: agent
define void @store_agent(ptr addrspace(1) %p, <4 x i32> %v) {
; GFX942-SDAG-LABEL: store_agent:
; GFX942-SDAG:       ; %bb.0:
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-SDAG-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off sc1
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX942-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-SDAG-LABEL: store_agent:
; GFX1012-SDAG:       ; %bb.0:
; GFX1012-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-SDAG-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off
; GFX1012-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-SDAG-LABEL: store_agent:
; GFX1100-SDAG:       ; %bb.0:
; GFX1100-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-SDAG-NEXT:    av_global_store_b128 v[0:1], v[2:5], off
; GFX1100-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-SDAG-LABEL: store_agent:
; GFX1250-SDAG:       ; %bb.0:
; GFX1250-SDAG-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-NEXT:    av_global_store_b128 v[0:1], v[2:5], off scope:SCOPE_DEV
; GFX1250-SDAG-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX942-ISEL-LABEL: store_agent:
; GFX942-ISEL:       ; %bb.0:
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-ISEL-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off sc1
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX942-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-ISEL-LABEL: store_agent:
; GFX1012-ISEL:       ; %bb.0:
; GFX1012-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-ISEL-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off
; GFX1012-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-ISEL-LABEL: store_agent:
; GFX1100-ISEL:       ; %bb.0:
; GFX1100-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-ISEL-NEXT:    av_global_store_b128 v[0:1], v[2:5], off
; GFX1100-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-ISEL-LABEL: store_agent:
; GFX1250-ISEL:       ; %bb.0:
; GFX1250-ISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-ISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-ISEL-NEXT:    av_global_store_b128 v[0:1], v[2:5], off scope:SCOPE_DEV
; GFX1250-ISEL-NEXT:    s_set_pc_i64 s[30:31]
  call void @llvm.amdgcn.av.global.store.b128(ptr addrspace(1) %p, <4 x i32> %v, metadata !2)
  ret void
}

; scope: system (empty string = system scope)
define void @store_system(ptr addrspace(1) %p, <4 x i32> %v) {
; GFX942-SDAG-LABEL: store_system:
; GFX942-SDAG:       ; %bb.0:
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-SDAG-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off sc0 sc1
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX942-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-SDAG-LABEL: store_system:
; GFX1012-SDAG:       ; %bb.0:
; GFX1012-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-SDAG-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off
; GFX1012-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-SDAG-LABEL: store_system:
; GFX1100-SDAG:       ; %bb.0:
; GFX1100-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-SDAG-NEXT:    av_global_store_b128 v[0:1], v[2:5], off
; GFX1100-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-SDAG-LABEL: store_system:
; GFX1250-SDAG:       ; %bb.0:
; GFX1250-SDAG-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-NEXT:    av_global_store_b128 v[0:1], v[2:5], off scope:SCOPE_SYS
; GFX1250-SDAG-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX942-ISEL-LABEL: store_system:
; GFX942-ISEL:       ; %bb.0:
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-ISEL-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off sc0 sc1
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX942-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-ISEL-LABEL: store_system:
; GFX1012-ISEL:       ; %bb.0:
; GFX1012-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-ISEL-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off
; GFX1012-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-ISEL-LABEL: store_system:
; GFX1100-ISEL:       ; %bb.0:
; GFX1100-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-ISEL-NEXT:    av_global_store_b128 v[0:1], v[2:5], off
; GFX1100-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-ISEL-LABEL: store_system:
; GFX1250-ISEL:       ; %bb.0:
; GFX1250-ISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-ISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-ISEL-NEXT:    av_global_store_b128 v[0:1], v[2:5], off scope:SCOPE_SYS
; GFX1250-ISEL-NEXT:    s_set_pc_i64 s[30:31]
  call void @llvm.amdgcn.av.global.store.b128(ptr addrspace(1) %p, <4 x i32> %v, metadata !3)
  ret void
}

; scope: singlethread
define void @store_singlethread(ptr addrspace(1) %p, <4 x i32> %v) {
; GFX942-SDAG-LABEL: store_singlethread:
; GFX942-SDAG:       ; %bb.0:
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-SDAG-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX942-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-SDAG-LABEL: store_singlethread:
; GFX1012-SDAG:       ; %bb.0:
; GFX1012-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-SDAG-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off
; GFX1012-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-SDAG-LABEL: store_singlethread:
; GFX1100-SDAG:       ; %bb.0:
; GFX1100-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-SDAG-NEXT:    av_global_store_b128 v[0:1], v[2:5], off
; GFX1100-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-SDAG-LABEL: store_singlethread:
; GFX1250-SDAG:       ; %bb.0:
; GFX1250-SDAG-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-NEXT:    av_global_store_b128 v[0:1], v[2:5], off
; GFX1250-SDAG-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX942-ISEL-LABEL: store_singlethread:
; GFX942-ISEL:       ; %bb.0:
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-ISEL-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX942-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-ISEL-LABEL: store_singlethread:
; GFX1012-ISEL:       ; %bb.0:
; GFX1012-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-ISEL-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off
; GFX1012-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-ISEL-LABEL: store_singlethread:
; GFX1100-ISEL:       ; %bb.0:
; GFX1100-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-ISEL-NEXT:    av_global_store_b128 v[0:1], v[2:5], off
; GFX1100-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-ISEL-LABEL: store_singlethread:
; GFX1250-ISEL:       ; %bb.0:
; GFX1250-ISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-ISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-ISEL-NEXT:    av_global_store_b128 v[0:1], v[2:5], off
; GFX1250-ISEL-NEXT:    s_set_pc_i64 s[30:31]
  call void @llvm.amdgcn.av.global.store.b128(ptr addrspace(1) %p, <4 x i32> %v, metadata !4)
  ret void
}

; scope: cluster
define void @store_cluster(ptr addrspace(1) %p, <4 x i32> %v) {
; GFX942-SDAG-LABEL: store_cluster:
; GFX942-SDAG:       ; %bb.0:
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-SDAG-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off sc1
; GFX942-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX942-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-SDAG-LABEL: store_cluster:
; GFX1012-SDAG:       ; %bb.0:
; GFX1012-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-SDAG-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off
; GFX1012-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-SDAG-LABEL: store_cluster:
; GFX1100-SDAG:       ; %bb.0:
; GFX1100-SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-SDAG-NEXT:    av_global_store_b128 v[0:1], v[2:5], off
; GFX1100-SDAG-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-SDAG-LABEL: store_cluster:
; GFX1250-SDAG:       ; %bb.0:
; GFX1250-SDAG-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX1250-SDAG-NEXT:    av_global_store_b128 v[0:1], v[2:5], off scope:SCOPE_SE
; GFX1250-SDAG-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX942-ISEL-LABEL: store_cluster:
; GFX942-ISEL:       ; %bb.0:
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX942-ISEL-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off sc1
; GFX942-ISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX942-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1012-ISEL-LABEL: store_cluster:
; GFX1012-ISEL:       ; %bb.0:
; GFX1012-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1012-ISEL-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off
; GFX1012-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1100-ISEL-LABEL: store_cluster:
; GFX1100-ISEL:       ; %bb.0:
; GFX1100-ISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1100-ISEL-NEXT:    av_global_store_b128 v[0:1], v[2:5], off
; GFX1100-ISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-ISEL-LABEL: store_cluster:
; GFX1250-ISEL:       ; %bb.0:
; GFX1250-ISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-ISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-ISEL-NEXT:    av_global_store_b128 v[0:1], v[2:5], off scope:SCOPE_SE
; GFX1250-ISEL-NEXT:    s_set_pc_i64 s[30:31]
  call void @llvm.amdgcn.av.global.store.b128(ptr addrspace(1) %p, <4 x i32> %v, metadata !5)
  ret void
}

!0 = !{!"wavefront"}
!1 = !{!"workgroup"}
!2 = !{!"agent"}
!3 = !{!""}
!4 = !{!"singlethread"}
!5 = !{!"cluster"}
