; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 -passes=amdgpu-codegenprepare %s | FileCheck %s

; Test that chained sliding window shuffles are folded to the shared operand.
; Pattern: shuffle(shuffle(A,B,M), shuffle(B,C,M), M) = B
; where M = <2,3,4,5> extracts upper half of first and lower half of second.

define void @test_sliding_window_direct(<4 x i8> %a, <4 x i8> %b, <4 x i8> %c, ptr addrspace(1) %out) {
; CHECK-LABEL: @test_sliding_window_direct(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    store <4 x i8> [[B:%.*]], ptr addrspace(1) [[OUT:%.*]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %s1 = shufflevector <4 x i8> %a, <4 x i8> %b, <4 x i32> <i32 2, i32 3, i32 4, i32 5>
  %s2 = shufflevector <4 x i8> %b, <4 x i8> %c, <4 x i32> <i32 2, i32 3, i32 4, i32 5>
  %result = shufflevector <4 x i8> %s1, <4 x i8> %s2, <4 x i32> <i32 2, i32 3, i32 4, i32 5>
  store <4 x i8> %result, ptr addrspace(1) %out
  ret void
}

define void @test_sliding_window_phi(<4 x i8> %a, <4 x i8> %b, <4 x i8> %c, <4 x i8> %d, <4 x i8> %e, <4 x i8> %f, ptr addrspace(1) %out, i1 %cond) {
; CHECK-LABEL: @test_sliding_window_phi(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[THEN:%.*]], label [[ELSE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    br label [[MERGE:%.*]]
; CHECK:       else:
; CHECK-NEXT:    br label [[MERGE]]
; CHECK:       merge:
; CHECK-NEXT:    [[SLIDING_MID:%.*]] = phi <4 x i8> [ [[B:%.*]], [[THEN]] ], [ [[E:%.*]], [[ELSE]] ]
; CHECK-NEXT:    store <4 x i8> [[SLIDING_MID]], ptr addrspace(1) [[OUT:%.*]], align 4
; CHECK-NEXT:    ret void
;
entry:
  br i1 %cond, label %then, label %else

then:
  %s1.then = shufflevector <4 x i8> %a, <4 x i8> %b, <4 x i32> <i32 2, i32 3, i32 4, i32 5>
  %s2.then = shufflevector <4 x i8> %b, <4 x i8> %c, <4 x i32> <i32 2, i32 3, i32 4, i32 5>
  br label %merge

else:
  %s1.else = shufflevector <4 x i8> %d, <4 x i8> %e, <4 x i32> <i32 2, i32 3, i32 4, i32 5>
  %s2.else = shufflevector <4 x i8> %e, <4 x i8> %f, <4 x i32> <i32 2, i32 3, i32 4, i32 5>
  br label %merge

merge:
  %phi1 = phi <4 x i8> [ %s1.then, %then ], [ %s1.else, %else ]
  %phi2 = phi <4 x i8> [ %s2.then, %then ], [ %s2.else, %else ]
  %result = shufflevector <4 x i8> %phi1, <4 x i8> %phi2, <4 x i32> <i32 2, i32 3, i32 4, i32 5>
  store <4 x i8> %result, ptr addrspace(1) %out
  ret void
}

; Negative test: shared operand doesn't match (B != C)
define <4 x i8> @test_no_shared_operand(<4 x i8> %a, <4 x i8> %b, <4 x i8> %c, <4 x i8> %d) {
; CHECK-LABEL: @test_no_shared_operand(
; CHECK-NEXT:    [[S1:%.*]] = shufflevector <4 x i8> [[A:%.*]], <4 x i8> [[B:%.*]], <4 x i32> <i32 2, i32 3, i32 4, i32 5>
; CHECK-NEXT:    [[S2:%.*]] = shufflevector <4 x i8> [[C:%.*]], <4 x i8> [[D:%.*]], <4 x i32> <i32 2, i32 3, i32 4, i32 5>
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <4 x i8> [[S1]], <4 x i8> [[S2]], <4 x i32> <i32 2, i32 3, i32 4, i32 5>
; CHECK-NEXT:    ret <4 x i8> [[RESULT]]
;
  %s1 = shufflevector <4 x i8> %a, <4 x i8> %b, <4 x i32> <i32 2, i32 3, i32 4, i32 5>
  %s2 = shufflevector <4 x i8> %c, <4 x i8> %d, <4 x i32> <i32 2, i32 3, i32 4, i32 5>
  %result = shufflevector <4 x i8> %s1, <4 x i8> %s2, <4 x i32> <i32 2, i32 3, i32 4, i32 5>
  ret <4 x i8> %result
}

; Negative test: inner shuffles have different mask
define <4 x i8> @test_different_inner_mask(<4 x i8> %a, <4 x i8> %b, <4 x i8> %c) {
; CHECK-LABEL: @test_different_inner_mask(
; CHECK-NEXT:    [[S1:%.*]] = shufflevector <4 x i8> [[A:%.*]], <4 x i8> [[B:%.*]], <4 x i32> <i32 1, i32 2, i32 3, i32 4>
; CHECK-NEXT:    [[S2:%.*]] = shufflevector <4 x i8> [[B]], <4 x i8> [[C:%.*]], <4 x i32> <i32 1, i32 2, i32 3, i32 4>
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <4 x i8> [[S1]], <4 x i8> [[S2]], <4 x i32> <i32 2, i32 3, i32 4, i32 5>
; CHECK-NEXT:    ret <4 x i8> [[RESULT]]
;
  %s1 = shufflevector <4 x i8> %a, <4 x i8> %b, <4 x i32> <i32 1, i32 2, i32 3, i32 4>
  %s2 = shufflevector <4 x i8> %b, <4 x i8> %c, <4 x i32> <i32 1, i32 2, i32 3, i32 4>
  %result = shufflevector <4 x i8> %s1, <4 x i8> %s2, <4 x i32> <i32 2, i32 3, i32 4, i32 5>
  ret <4 x i8> %result
}
