; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -passes=amdgpu-late-codegenprepare %s | FileCheck %s

; A shufflevector constant operand made of only poison and zero lanes (a padded
; WMMA operand) is canonicalized to a full zeroinitializer, giving ISel a single
; uniform zero.

define <16 x bfloat> @canon_mixed_poison_zero(<16 x bfloat> %v) {
; CHECK-LABEL: define <16 x bfloat> @canon_mixed_poison_zero(
; CHECK-SAME: <16 x bfloat> [[V:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[R:%.*]] = shufflevector <16 x bfloat> [[V]], <16 x bfloat> zeroinitializer, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
; CHECK-NEXT:    ret <16 x bfloat> [[R]]
;
  %r = shufflevector <16 x bfloat> %v, <16 x bfloat> <bfloat poison, bfloat poison, bfloat poison, bfloat poison, bfloat poison, bfloat poison, bfloat poison, bfloat poison, bfloat 0.0, bfloat 0.0, bfloat 0.0, bfloat 0.0, bfloat 0.0, bfloat 0.0, bfloat 0.0, bfloat 0.0>, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <16 x bfloat> %r
}

; All-poison operand: no zero lane, so it must NOT be canonicalized.
define <8 x bfloat> @no_canon_all_poison(<8 x bfloat> %v) {
; CHECK-LABEL: define <8 x bfloat> @no_canon_all_poison(
; CHECK-SAME: <8 x bfloat> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[R:%.*]] = shufflevector <8 x bfloat> [[V]], <8 x bfloat> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
; CHECK-NEXT:    ret <8 x bfloat> [[R]]
;
  %r = shufflevector <8 x bfloat> %v, <8 x bfloat> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
  ret <8 x bfloat> %r
}

; Operand has a nonzero, non-poison lane, so it must NOT be canonicalized.
define <4 x float> @no_canon_nonzero_lane(<4 x float> %v) {
; CHECK-LABEL: define <4 x float> @no_canon_nonzero_lane(
; CHECK-SAME: <4 x float> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[R:%.*]] = shufflevector <4 x float> [[V]], <4 x float> <float poison, float poison, float 1.000000e+00, float 0.000000e+00>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
; CHECK-NEXT:    ret <4 x float> [[R]]
;
  %r = shufflevector <4 x float> %v, <4 x float> <float poison, float poison, float 1.0, float 0.0>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
  ret <4 x float> %r
}
