# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -amdgpu-expert-scheduling-mode=true -run-pass=amdgpu-pre-ra-optimizations,greedy,machineverifier,virtregrewriter,post-RA-hazard-rec,si-insert-waitcnts -amdgpu-anti-hints-for-va-vdst=true %s -o - | FileCheck %s --check-prefix=CHECK
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -amdgpu-expert-scheduling-mode=true -run-pass=amdgpu-pre-ra-optimizations,greedy,machineverifier,virtregrewriter,post-RA-hazard-rec,si-insert-waitcnts %s -o - | FileCheck %s --check-prefix=CHECK-NO-ANTIHINT

# Test anti-hints for VA-VDST WAR hazards on gfx1250.
#
# When a VALU instruction reads from a VGPR and a subsequent memory load writes
# to a VGPR, the compiler must avoid allocating both to the same physical register.
# If they overlap, hardware requires s_wait_alu va_vdst to resolve the WAR hazard.
# Anti-hints guide the register allocator to avoid this overlap.
#
# With anti-hints enabled:
#   - VALU source and memory load destination get different registers
#   - No register overlap means no WAR hazard
#
# Without anti-hints:
#   - Register allocator may reuse VALU source register for memory load destination
#   - This creates a WAR hazard (VALU reads register, then load overwrites it)
#
# Test scenarios:
#   - VALU (V_ADD_U32) followed by DS_READ_B128_gfx9
#   - VALU (V_ADD_U32) followed by BUFFER_LOAD_DWORD_OFFEN
#   - VALU (V_PK_ADD_F32) followed by DS_READ_B128_gfx9
#   - V_WMMA followed by DS_READ_B128_gfx9

--- |
  target triple = "amdgcn-amd-amdhsa"

  define amdgpu_kernel void @test_valu_dsread_anti_hints() #0 {
  bb.0:
    ret void
  }

  define amdgpu_kernel void @test_valu_buffer_load_anti_hints() #0 {
  bb.0:
    ret void
  }

  define amdgpu_kernel void @test_pk_add_dsread_anti_hints() #0 {
  bb.0:
    ret void
  }

  define amdgpu_kernel void @test_wmma_dsread_anti_hints() #0 {
  bb.0:
    ret void
  }

  attributes #0 = {nounwind "amdgpu-agpr-alloc"="0" "frame-pointer"="none"}

...
---
# Test: V_ADD_U32 (VALU) followed by DS_READ_B128_gfx9
# With anti-hints: %0 allocated to vgpr4, DS_READ dest to vgpr0-3 (no overlap)
# Without anti-hints: %0 allocated to vgpr0, DS_READ dest to vgpr0-3 (overlaps!)
name:            test_valu_dsread_anti_hints
tracksRegLiveness: true
body:             |
  bb.0:
    ; CHECK-LABEL: name: test_valu_dsread_anti_hints
    ; CHECK: liveins: $vgpr10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $vgpr4 = IMPLICIT_DEF
    ; CHECK-NEXT: S_SETREG_IMM32_B32 2, 2074, implicit-def $mode, implicit $mode
    ; CHECK-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; CHECK-NEXT: S_WAIT_KMCNT 0
    ; CHECK-NEXT: renamable $vgpr5 = V_ADD_U32_e32 1, $vgpr4, implicit $exec
    ; CHECK-NEXT: renamable $vgpr4 = V_ADD_U32_e32 2, killed $vgpr4, implicit $exec
    ; CHECK-NEXT: renamable $vgpr0_vgpr1_vgpr2_vgpr3 = DS_READ_B128_gfx9 killed renamable $vgpr10, 0, 0, implicit $exec
    ; CHECK-NEXT: S_ENDPGM 0, implicit killed renamable $vgpr0_vgpr1_vgpr2_vgpr3, implicit killed renamable $vgpr5, implicit killed renamable $vgpr4
    ;
    ; CHECK-NO-ANTIHINT-LABEL: name: test_valu_dsread_anti_hints
    ; CHECK-NO-ANTIHINT: liveins: $vgpr10
    ; CHECK-NO-ANTIHINT-NEXT: {{  $}}
    ; CHECK-NO-ANTIHINT-NEXT: renamable $vgpr0 = IMPLICIT_DEF
    ; CHECK-NO-ANTIHINT-NEXT: S_SETREG_IMM32_B32 2, 2074, implicit-def $mode, implicit $mode
    ; CHECK-NO-ANTIHINT-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; CHECK-NO-ANTIHINT-NEXT: S_WAIT_KMCNT 0
    ; CHECK-NO-ANTIHINT-NEXT: renamable $vgpr4 = V_ADD_U32_e32 1, $vgpr0, implicit $exec
    ; CHECK-NO-ANTIHINT-NEXT: renamable $vgpr5 = V_ADD_U32_e32 2, killed $vgpr0, implicit $exec
    ; CHECK-NO-ANTIHINT-NEXT: renamable $vgpr0_vgpr1_vgpr2_vgpr3 = DS_READ_B128_gfx9 killed renamable $vgpr10, 0, 0, implicit $exec
    ; CHECK-NO-ANTIHINT-NEXT: S_ENDPGM 0, implicit killed renamable $vgpr0_vgpr1_vgpr2_vgpr3, implicit killed renamable $vgpr4, implicit killed renamable $vgpr5
    liveins:$vgpr10

    %0:vgpr_32 = IMPLICIT_DEF
    %4:vgpr_32 = COPY $vgpr10
    %1:vgpr_32 = V_ADD_U32_e32 1, %0, implicit $exec
    %2:vgpr_32 = V_ADD_U32_e32 2, %0, implicit $exec
    %3:vreg_128_align2 = DS_READ_B128_gfx9 %4:vgpr_32, 0, 0, implicit $exec
    S_ENDPGM 0, implicit %3, implicit %1, implicit %2
...
---
# Test: V_ADD_U32 (VALU) followed by BUFFER_LOAD_DWORD_OFFEN
# With anti-hints: %0 gets vgpr0, BUFFER_LOAD dest gets vgpr3 (no overlap)
# Without anti-hints: %0 gets vgpr0, BUFFER_LOAD dest gets vgpr0 (overlaps!)
name:            test_valu_buffer_load_anti_hints
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $vgpr10, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr4

    ; CHECK-LABEL: name: test_valu_buffer_load_anti_hints
    ; CHECK: liveins: $sgpr4, $vgpr10, $sgpr0_sgpr1_sgpr2_sgpr3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $vgpr0 = IMPLICIT_DEF
    ; CHECK-NEXT: S_SETREG_IMM32_B32 2, 2074, implicit-def $mode, implicit $mode
    ; CHECK-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; CHECK-NEXT: S_WAIT_KMCNT 0
    ; CHECK-NEXT: renamable $vgpr1 = V_ADD_U32_e32 1, $vgpr0, implicit $exec
    ; CHECK-NEXT: renamable $vgpr0 = V_ADD_U32_e32 2, killed $vgpr0, implicit $exec
    ; CHECK-NEXT: renamable $vgpr2 = BUFFER_LOAD_DWORD_OFFEN killed renamable $vgpr10, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr4, 0, 0, 0, implicit $exec
    ; CHECK-NEXT: S_ENDPGM 0, implicit killed renamable $vgpr2, implicit killed renamable $vgpr1, implicit killed renamable $vgpr0
    ;
    ; CHECK-NO-ANTIHINT-LABEL: name: test_valu_buffer_load_anti_hints
    ; CHECK-NO-ANTIHINT: liveins: $sgpr4, $vgpr10, $sgpr0_sgpr1_sgpr2_sgpr3
    ; CHECK-NO-ANTIHINT-NEXT: {{  $}}
    ; CHECK-NO-ANTIHINT-NEXT: renamable $vgpr0 = IMPLICIT_DEF
    ; CHECK-NO-ANTIHINT-NEXT: S_SETREG_IMM32_B32 2, 2074, implicit-def $mode, implicit $mode
    ; CHECK-NO-ANTIHINT-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; CHECK-NO-ANTIHINT-NEXT: S_WAIT_KMCNT 0
    ; CHECK-NO-ANTIHINT-NEXT: renamable $vgpr1 = V_ADD_U32_e32 1, $vgpr0, implicit $exec
    ; CHECK-NO-ANTIHINT-NEXT: renamable $vgpr0 = V_ADD_U32_e32 2, killed $vgpr0, implicit $exec
    ; CHECK-NO-ANTIHINT-NEXT: renamable $vgpr2 = BUFFER_LOAD_DWORD_OFFEN killed renamable $vgpr10, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr4, 0, 0, 0, implicit $exec
    ; CHECK-NO-ANTIHINT-NEXT: S_ENDPGM 0, implicit killed renamable $vgpr2, implicit killed renamable $vgpr1, implicit killed renamable $vgpr0
    %0:vgpr_32 = IMPLICIT_DEF
    %4:vgpr_32 = COPY $vgpr10
    %1:vgpr_32 = V_ADD_U32_e32 1, %0, implicit $exec
    %2:vgpr_32 = V_ADD_U32_e32 2, %0, implicit $exec
    %3:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %4, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr4, 0, 0, 0, implicit $exec
    S_ENDPGM 0, implicit %3, implicit %1, implicit %2
...
---
# Test: V_PK_ADD_F32 (packed VALU) followed by DS_READ_B128_gfx9
# With anti-hints: V_PK_ADD sources get vgpr4-7, DS_READ dest gets vgpr0-3 (no overlap)
# Without anti-hints: V_PK_ADD sources get vgpr0-3, DS_READ dest gets vgpr0-3 (overlaps!)
name:            test_pk_add_dsread_anti_hints
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $vgpr10

    ; CHECK-LABEL: name: test_pk_add_dsread_anti_hints
    ; CHECK: liveins: $vgpr10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $vgpr4_vgpr5 = IMPLICIT_DEF
    ; CHECK-NEXT: renamable $vgpr6_vgpr7 = IMPLICIT_DEF
    ; CHECK-NEXT: S_SETREG_IMM32_B32 2, 2074, implicit-def $mode, implicit $mode
    ; CHECK-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; CHECK-NEXT: S_WAIT_KMCNT 0
    ; CHECK-NEXT: renamable $vgpr4_vgpr5 = V_PK_ADD_F32 8, killed $vgpr4_vgpr5, 8, killed $vgpr6_vgpr7, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; CHECK-NEXT: renamable $vgpr0_vgpr1_vgpr2_vgpr3 = DS_READ_B128_gfx9 killed renamable $vgpr10, 0, 0, implicit $exec
    ; CHECK-NEXT: S_ENDPGM 0, implicit killed renamable $vgpr4_vgpr5, implicit killed renamable $vgpr0_vgpr1_vgpr2_vgpr3
    ;
    ; CHECK-NO-ANTIHINT-LABEL: name: test_pk_add_dsread_anti_hints
    ; CHECK-NO-ANTIHINT: liveins: $vgpr10
    ; CHECK-NO-ANTIHINT-NEXT: {{  $}}
    ; CHECK-NO-ANTIHINT-NEXT: renamable $vgpr0_vgpr1 = IMPLICIT_DEF
    ; CHECK-NO-ANTIHINT-NEXT: renamable $vgpr2_vgpr3 = IMPLICIT_DEF
    ; CHECK-NO-ANTIHINT-NEXT: S_SETREG_IMM32_B32 2, 2074, implicit-def $mode, implicit $mode
    ; CHECK-NO-ANTIHINT-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; CHECK-NO-ANTIHINT-NEXT: S_WAIT_KMCNT 0
    ; CHECK-NO-ANTIHINT-NEXT: renamable $vgpr4_vgpr5 = V_PK_ADD_F32 8, killed $vgpr0_vgpr1, 8, killed $vgpr2_vgpr3, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; CHECK-NO-ANTIHINT-NEXT: renamable $vgpr0_vgpr1_vgpr2_vgpr3 = DS_READ_B128_gfx9 killed renamable $vgpr10, 0, 0, implicit $exec
    ; CHECK-NO-ANTIHINT-NEXT: S_ENDPGM 0, implicit killed renamable $vgpr4_vgpr5, implicit killed renamable $vgpr0_vgpr1_vgpr2_vgpr3
    %0:vreg_64_align2 = IMPLICIT_DEF
    %1:vreg_64_align2 = IMPLICIT_DEF
    %2:vgpr_32 = COPY $vgpr10
    %3:vreg_64_align2 = V_PK_ADD_F32 8, %0, 8, %1, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %4:vreg_128_align2 = DS_READ_B128_gfx9 %2:vgpr_32, 0, 0, implicit $exec
    S_ENDPGM 0, implicit %3, implicit %4
...
---
# Test: V_WMMA_F32_16X16X32_BF16 (WMMA VALU) followed by DS_READ_B128_gfx9
# With anti-hints: DS_READ dest gets vgpr24-27 (no overlap with WMMA sources)
# Without anti-hints: Same allocation - register pressure makes anti-hints less visible here
name:            test_wmma_dsread_anti_hints
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $vgpr32

    ; CHECK-LABEL: name: test_wmma_dsread_anti_hints
    ; CHECK: liveins: $vgpr32
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7 = IMPLICIT_DEF
    ; CHECK-NEXT: renamable $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15 = IMPLICIT_DEF
    ; CHECK-NEXT: renamable $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = IMPLICIT_DEF
    ; CHECK-NEXT: S_SETREG_IMM32_B32 2, 2074, implicit-def $mode, implicit $mode
    ; CHECK-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; CHECK-NEXT: S_WAIT_KMCNT 0
    ; CHECK-NEXT: early-clobber renamable $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; CHECK-NEXT: renamable $vgpr24_vgpr25_vgpr26_vgpr27 = DS_READ_B128_gfx9 killed renamable $vgpr32, 0, 0, implicit $exec
    ; CHECK-NEXT: S_ENDPGM 0, implicit killed renamable $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, implicit killed renamable $vgpr24_vgpr25_vgpr26_vgpr27
    ;
    ; CHECK-NO-ANTIHINT-LABEL: name: test_wmma_dsread_anti_hints
    ; CHECK-NO-ANTIHINT: liveins: $vgpr32
    ; CHECK-NO-ANTIHINT-NEXT: {{  $}}
    ; CHECK-NO-ANTIHINT-NEXT: renamable $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7 = IMPLICIT_DEF
    ; CHECK-NO-ANTIHINT-NEXT: renamable $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15 = IMPLICIT_DEF
    ; CHECK-NO-ANTIHINT-NEXT: renamable $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = IMPLICIT_DEF
    ; CHECK-NO-ANTIHINT-NEXT: S_SETREG_IMM32_B32 2, 2074, implicit-def $mode, implicit $mode
    ; CHECK-NO-ANTIHINT-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; CHECK-NO-ANTIHINT-NEXT: S_WAIT_KMCNT 0
    ; CHECK-NO-ANTIHINT-NEXT: early-clobber renamable $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; CHECK-NO-ANTIHINT-NEXT: renamable $vgpr24_vgpr25_vgpr26_vgpr27 = DS_READ_B128_gfx9 killed renamable $vgpr32, 0, 0, implicit $exec
    ; CHECK-NO-ANTIHINT-NEXT: S_ENDPGM 0, implicit killed renamable $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, implicit killed renamable $vgpr24_vgpr25_vgpr26_vgpr27
    %0:vreg_256_align2 = IMPLICIT_DEF
    %1:vreg_256_align2 = IMPLICIT_DEF
    %2:vgpr_32 = COPY $vgpr32
    %3:vreg_256_align2 = IMPLICIT_DEF
    %4:vreg_256_align2 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr 8, %0, 8, %1, 8, %3, 0, 0, 0, 0, implicit $exec
    %5:vreg_128_align2 = DS_READ_B128_gfx9 %2:vgpr_32, 0, 0, implicit $exec
    S_ENDPGM 0, implicit %4, implicit %5
...
