; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: sed 's/SRAMECC/0/' %s | llc -mtriple=amdgpu12.50 -mattr=+real-true16 | FileCheck -check-prefix=SRAMECC-OFF %s
; RUN: sed 's/SRAMECC/1/' %s | llc -mtriple=amdgpu12.50 -mattr=+real-true16 | FileCheck -check-prefix=SRAMECC-ON %s
; RUN: sed 's/SRAMECC/0/' %s | llc -global-isel -mtriple=amdgpu12.50 -mattr=+real-true16 | FileCheck -check-prefix=SRAMECC-OFF %s
; RUN: sed 's/SRAMECC/1/' %s | llc -global-isel -mtriple=amdgpu12.50 -mattr=+real-true16 | FileCheck -check-prefix=SRAMECC-ON %s

define i16 @atomic_load_i16_global(ptr addrspace(1) %p) {
; SRAMECC-OFF-LABEL: atomic_load_i16_global:
; SRAMECC-OFF:       ; %bb.0:
; SRAMECC-OFF-NEXT:    s_wait_loadcnt_dscnt 0x0
; SRAMECC-OFF-NEXT:    s_wait_kmcnt 0x0
; SRAMECC-OFF-NEXT:    global_load_d16_b16 v0, v[0:1], off scope:SCOPE_SYS
; SRAMECC-OFF-NEXT:    s_wait_loadcnt 0x0
; SRAMECC-OFF-NEXT:    s_set_pc_i64 s[30:31]
;
; SRAMECC-ON-LABEL: atomic_load_i16_global:
; SRAMECC-ON:       ; %bb.0:
; SRAMECC-ON-NEXT:    s_wait_loadcnt_dscnt 0x0
; SRAMECC-ON-NEXT:    s_wait_kmcnt 0x0
; SRAMECC-ON-NEXT:    global_load_u16 v0, v[0:1], off scope:SCOPE_SYS
; SRAMECC-ON-NEXT:    s_wait_loadcnt 0x0
; SRAMECC-ON-NEXT:    s_set_pc_i64 s[30:31]
  %v = load atomic i16, ptr addrspace(1) %p monotonic, align 2
  ret i16 %v
}

define half @atomic_load_f16_global(ptr addrspace(1) %p) {
; SRAMECC-OFF-LABEL: atomic_load_f16_global:
; SRAMECC-OFF:       ; %bb.0:
; SRAMECC-OFF-NEXT:    s_wait_loadcnt_dscnt 0x0
; SRAMECC-OFF-NEXT:    s_wait_kmcnt 0x0
; SRAMECC-OFF-NEXT:    global_load_d16_b16 v0, v[0:1], off scope:SCOPE_SYS
; SRAMECC-OFF-NEXT:    s_wait_loadcnt 0x0
; SRAMECC-OFF-NEXT:    s_set_pc_i64 s[30:31]
;
; SRAMECC-ON-LABEL: atomic_load_f16_global:
; SRAMECC-ON:       ; %bb.0:
; SRAMECC-ON-NEXT:    s_wait_loadcnt_dscnt 0x0
; SRAMECC-ON-NEXT:    s_wait_kmcnt 0x0
; SRAMECC-ON-NEXT:    global_load_u16 v0, v[0:1], off scope:SCOPE_SYS
; SRAMECC-ON-NEXT:    s_wait_loadcnt 0x0
; SRAMECC-ON-NEXT:    s_set_pc_i64 s[30:31]
  %v = load atomic half, ptr addrspace(1) %p monotonic, align 2
  ret half %v
}

define bfloat @atomic_load_bf16_global(ptr addrspace(1) %p) {
; SRAMECC-OFF-LABEL: atomic_load_bf16_global:
; SRAMECC-OFF:       ; %bb.0:
; SRAMECC-OFF-NEXT:    s_wait_loadcnt_dscnt 0x0
; SRAMECC-OFF-NEXT:    s_wait_kmcnt 0x0
; SRAMECC-OFF-NEXT:    global_load_d16_b16 v0, v[0:1], off scope:SCOPE_SYS
; SRAMECC-OFF-NEXT:    s_wait_loadcnt 0x0
; SRAMECC-OFF-NEXT:    s_set_pc_i64 s[30:31]
;
; SRAMECC-ON-LABEL: atomic_load_bf16_global:
; SRAMECC-ON:       ; %bb.0:
; SRAMECC-ON-NEXT:    s_wait_loadcnt_dscnt 0x0
; SRAMECC-ON-NEXT:    s_wait_kmcnt 0x0
; SRAMECC-ON-NEXT:    global_load_u16 v0, v[0:1], off scope:SCOPE_SYS
; SRAMECC-ON-NEXT:    s_wait_loadcnt 0x0
; SRAMECC-ON-NEXT:    s_set_pc_i64 s[30:31]
  %v = load atomic bfloat, ptr addrspace(1) %p monotonic, align 2
  ret bfloat %v
}

define i16 @atomic_load_i16_flat(ptr %p) {
; SRAMECC-OFF-LABEL: atomic_load_i16_flat:
; SRAMECC-OFF:       ; %bb.0:
; SRAMECC-OFF-NEXT:    s_wait_loadcnt_dscnt 0x0
; SRAMECC-OFF-NEXT:    s_wait_kmcnt 0x0
; SRAMECC-OFF-NEXT:    flat_load_d16_b16 v0, v[0:1] scope:SCOPE_SYS
; SRAMECC-OFF-NEXT:    s_wait_loadcnt_dscnt 0x0
; SRAMECC-OFF-NEXT:    s_set_pc_i64 s[30:31]
;
; SRAMECC-ON-LABEL: atomic_load_i16_flat:
; SRAMECC-ON:       ; %bb.0:
; SRAMECC-ON-NEXT:    s_wait_loadcnt_dscnt 0x0
; SRAMECC-ON-NEXT:    s_wait_kmcnt 0x0
; SRAMECC-ON-NEXT:    flat_load_u16 v0, v[0:1] scope:SCOPE_SYS
; SRAMECC-ON-NEXT:    s_wait_loadcnt_dscnt 0x0
; SRAMECC-ON-NEXT:    s_set_pc_i64 s[30:31]
  %v = load atomic i16, ptr %p monotonic, align 2
  ret i16 %v
}

define half @atomic_load_f16_local(ptr addrspace(3) %p) {
; SRAMECC-OFF-LABEL: atomic_load_f16_local:
; SRAMECC-OFF:       ; %bb.0:
; SRAMECC-OFF-NEXT:    s_wait_loadcnt_dscnt 0x0
; SRAMECC-OFF-NEXT:    s_wait_kmcnt 0x0
; SRAMECC-OFF-NEXT:    ds_load_u16_d16 v0, v0
; SRAMECC-OFF-NEXT:    s_wait_dscnt 0x0
; SRAMECC-OFF-NEXT:    s_set_pc_i64 s[30:31]
;
; SRAMECC-ON-LABEL: atomic_load_f16_local:
; SRAMECC-ON:       ; %bb.0:
; SRAMECC-ON-NEXT:    s_wait_loadcnt_dscnt 0x0
; SRAMECC-ON-NEXT:    s_wait_kmcnt 0x0
; SRAMECC-ON-NEXT:    ds_load_u16 v0, v0
; SRAMECC-ON-NEXT:    s_wait_dscnt 0x0
; SRAMECC-ON-NEXT:    s_set_pc_i64 s[30:31]
  %v = load atomic half, ptr addrspace(3) %p monotonic, align 2
  ret half %v
}

define void @atomic_store_i16_global(ptr addrspace(1) %p, i16 %v) {
; SRAMECC-OFF-LABEL: atomic_store_i16_global:
; SRAMECC-OFF:       ; %bb.0:
; SRAMECC-OFF-NEXT:    s_wait_loadcnt_dscnt 0x0
; SRAMECC-OFF-NEXT:    s_wait_kmcnt 0x0
; SRAMECC-OFF-NEXT:    global_store_b16 v[0:1], v2, off scope:SCOPE_SYS
; SRAMECC-OFF-NEXT:    s_set_pc_i64 s[30:31]
;
; SRAMECC-ON-LABEL: atomic_store_i16_global:
; SRAMECC-ON:       ; %bb.0:
; SRAMECC-ON-NEXT:    s_wait_loadcnt_dscnt 0x0
; SRAMECC-ON-NEXT:    s_wait_kmcnt 0x0
; SRAMECC-ON-NEXT:    global_store_b16 v[0:1], v2, off scope:SCOPE_SYS
; SRAMECC-ON-NEXT:    s_set_pc_i64 s[30:31]
  store atomic i16 %v, ptr addrspace(1) %p monotonic, align 2
  ret void
}

define void @atomic_store_f16_global(ptr addrspace(1) %p, half %v) {
; SRAMECC-OFF-LABEL: atomic_store_f16_global:
; SRAMECC-OFF:       ; %bb.0:
; SRAMECC-OFF-NEXT:    s_wait_loadcnt_dscnt 0x0
; SRAMECC-OFF-NEXT:    s_wait_kmcnt 0x0
; SRAMECC-OFF-NEXT:    global_store_b16 v[0:1], v2, off scope:SCOPE_SYS
; SRAMECC-OFF-NEXT:    s_set_pc_i64 s[30:31]
;
; SRAMECC-ON-LABEL: atomic_store_f16_global:
; SRAMECC-ON:       ; %bb.0:
; SRAMECC-ON-NEXT:    s_wait_loadcnt_dscnt 0x0
; SRAMECC-ON-NEXT:    s_wait_kmcnt 0x0
; SRAMECC-ON-NEXT:    global_store_b16 v[0:1], v2, off scope:SCOPE_SYS
; SRAMECC-ON-NEXT:    s_set_pc_i64 s[30:31]
  store atomic half %v, ptr addrspace(1) %p monotonic, align 2
  ret void
}

define void @atomic_store_bf16_local(ptr addrspace(3) %p, bfloat %v) {
; SRAMECC-OFF-LABEL: atomic_store_bf16_local:
; SRAMECC-OFF:       ; %bb.0:
; SRAMECC-OFF-NEXT:    s_wait_loadcnt_dscnt 0x0
; SRAMECC-OFF-NEXT:    s_wait_kmcnt 0x0
; SRAMECC-OFF-NEXT:    ds_store_b16 v0, v1
; SRAMECC-OFF-NEXT:    s_wait_dscnt 0x0
; SRAMECC-OFF-NEXT:    s_set_pc_i64 s[30:31]
;
; SRAMECC-ON-LABEL: atomic_store_bf16_local:
; SRAMECC-ON:       ; %bb.0:
; SRAMECC-ON-NEXT:    s_wait_loadcnt_dscnt 0x0
; SRAMECC-ON-NEXT:    s_wait_kmcnt 0x0
; SRAMECC-ON-NEXT:    ds_store_b16 v0, v1
; SRAMECC-ON-NEXT:    s_wait_dscnt 0x0
; SRAMECC-ON-NEXT:    s_set_pc_i64 s[30:31]
  store atomic bfloat %v, ptr addrspace(3) %p monotonic, align 2
  ret void
}

!llvm.module.flags = !{!0}
!0 = !{i32 1, !"amdgpu.sramecc", i32 SRAMECC}
