# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=amdgcn -mcpu=gfx1250 -run-pass=machine-scheduler -amdgpu-sched-strategy=coexec -verify-misched %s -o - | FileCheck -check-prefix=COEXEC %s

# Test for the missed-slots heuristic in tryEffectiveStall.
#
# Uses V_WMMA_SCALE_F32_16X16X128_F8F6F4 which has pattern 0EEIEEIIVV.
# The missed-slots heuristic penalizes scheduling DS when the next
# slot is an I slot, because DS doesn't benefit from VALU/TRANS capability.
#
# This test verifies the scheduler runs correctly with the missed-slots
# heuristic enabled. VALU instructions can only execute in I slots
# (stages 3, 6, 7 for this pattern), while DS can execute in E or I slots.
# The heuristic ensures I slots are reserved for VALU when possible.

--- |
  define void @wmma_with_ds_and_valu() #0 { ret void }

  attributes #0 = { "amdgpu-waves-per-eu"="1,1" }
...

---
name: wmma_with_ds_and_valu
tracksRegLiveness: true
body: |
  ; COEXEC-LABEL: name: wmma_with_ds_and_valu
  ; COEXEC: bb.0:
  ; COEXEC-NEXT:   successors: %bb.1(0x80000000)
  ; COEXEC-NEXT: {{  $}}
  ; COEXEC-NEXT:   [[DEF:%[0-9]+]]:vreg_512_align2 = IMPLICIT_DEF
  ; COEXEC-NEXT:   [[DEF1:%[0-9]+]]:vreg_512_align2 = IMPLICIT_DEF
  ; COEXEC-NEXT:   [[DEF2:%[0-9]+]]:vreg_256_align2 = IMPLICIT_DEF
  ; COEXEC-NEXT:   [[DEF3:%[0-9]+]]:vgpr_32_lo256 = IMPLICIT_DEF
  ; COEXEC-NEXT:   [[DEF4:%[0-9]+]]:vgpr_32_lo256 = IMPLICIT_DEF
  ; COEXEC-NEXT:   [[DEF5:%[0-9]+]]:vgpr_32 = IMPLICIT_DEF
  ; COEXEC-NEXT:   [[DEF6:%[0-9]+]]:vgpr_32 = IMPLICIT_DEF
  ; COEXEC-NEXT:   [[DEF7:%[0-9]+]]:vgpr_32 = IMPLICIT_DEF
  ; COEXEC-NEXT:   [[DEF8:%[0-9]+]]:sreg_32 = IMPLICIT_DEF
  ; COEXEC-NEXT:   [[DEF9:%[0-9]+]]:sreg_32 = IMPLICIT_DEF
  ; COEXEC-NEXT:   [[S_ADD_I32_:%[0-9]+]]:sreg_32 = S_ADD_I32 [[DEF8]], [[DEF9]], implicit-def dead $scc
  ; COEXEC-NEXT:   dead [[S_ADD_I32_1:%[0-9]+]]:sreg_32 = S_ADD_I32 [[S_ADD_I32_]], [[DEF9]], implicit-def dead $scc
  ; COEXEC-NEXT:   S_BRANCH %bb.1
  ; COEXEC-NEXT: {{  $}}
  ; COEXEC-NEXT: bb.1:
  ; COEXEC-NEXT:   early-clobber %12:vreg_256_align2 = V_WMMA_SCALE_F32_16X16X128_F8F6F4_f8_f8_w32_threeaddr [[DEF]], [[DEF1]], 0, [[DEF2]], [[DEF3]], [[DEF4]], 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, implicit $exec
  ; COEXEC-NEXT:   [[DS_READ_B128_gfx9_:%[0-9]+]]:vreg_128_lo256_align2 = DS_READ_B128_gfx9 [[DEF5]], 0, 0, implicit $exec
  ; COEXEC-NEXT:   [[DS_READ_B128_gfx9_1:%[0-9]+]]:vreg_128_lo256_align2 = DS_READ_B128_gfx9 [[DEF5]], 0, 0, implicit $exec
  ; COEXEC-NEXT:   [[DS_READ_B128_gfx9_2:%[0-9]+]]:vreg_128_lo256_align2 = DS_READ_B128_gfx9 [[DEF5]], 0, 0, implicit $exec
  ; COEXEC-NEXT:   [[V_ADD_F32_e64_:%[0-9]+]]:vgpr_32 = V_ADD_F32_e64 0, [[DEF6]], 0, [[DEF7]], 0, 0, implicit $mode, implicit $exec
  ; COEXEC-NEXT:   S_ENDPGM 0, implicit %12, implicit [[DS_READ_B128_gfx9_]], implicit [[DS_READ_B128_gfx9_1]], implicit [[DS_READ_B128_gfx9_2]], implicit [[V_ADD_F32_e64_]]
  bb.0:
    successors: %bb.1
    %0:vreg_512_align2 = IMPLICIT_DEF
    %1:vreg_512_align2 = IMPLICIT_DEF
    %2:vreg_256_align2 = IMPLICIT_DEF
    %3:vgpr_32_lo256 = IMPLICIT_DEF
    %4:vgpr_32_lo256 = IMPLICIT_DEF
    %5:vgpr_32 = IMPLICIT_DEF
    %6:vgpr_32 = IMPLICIT_DEF
    %7:vgpr_32 = IMPLICIT_DEF
    %8:sreg_32 = IMPLICIT_DEF
    %9:sreg_32 = IMPLICIT_DEF
    %10:sreg_32 = S_ADD_I32 %8, %9, implicit-def dead $scc
    %11:sreg_32 = S_ADD_I32 %10, %9, implicit-def dead $scc
    S_BRANCH %bb.1

  bb.1:
    ; WMMA followed by SALU chain, independent DS and independent VALU.
    ; DS executes in E slot (stage 1), VALU waits for I slot (stage 3).
    ; The scheduler correctly places VALU in the I slot.
    %12:vreg_256_align2 = V_WMMA_SCALE_F32_16X16X128_F8F6F4_f8_f8_w32_threeaddr %0, %1, 0, %2, %3, %4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, implicit $exec
    %13:vreg_128_lo256_align2 = DS_READ_B128_gfx9 %5, 0, 0, implicit $exec
    %14:vreg_128_lo256_align2 = DS_READ_B128_gfx9 %5, 0, 0, implicit $exec
    %15:vreg_128_lo256_align2 = DS_READ_B128_gfx9 %5, 0, 0, implicit $exec
    %16:vgpr_32 = V_ADD_F32_e64 0, %6, 0, %7, 0, 0, implicit $mode, implicit $exec
    S_ENDPGM 0, implicit %12, implicit %13, implicit %14, implicit %15, implicit %16
...
