; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -O0 -amdgpu-scalarize-global-loads=false -mtriple=amdgcn -mcpu=gfx900 -mattr=-flat-for-global -stop-after=regallocfast < %s | FileCheck -check-prefixes=GCN %s

; Verify that we consider the xor at the end of the waterfall loop emitted for
; divergent indirect addressing as a terminator.

declare i32 @llvm.amdgcn.workitem.id.x() #1

; There should be no spill code inserted between the xor and the real terminator
define amdgpu_kernel void @extract_w_offset_vgpr(ptr addrspace(1) %out) {
  ; GCN-LABEL: name: extract_w_offset_vgpr
  ; GCN: bb.0.entry:
  ; GCN-NEXT:   liveins: $vgpr0, $sgpr4_sgpr5
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[COPY:%[0-9]+]]:vgpr_32(s32) = COPY killed $vgpr0
  ; GCN-NEXT:   early-clobber renamable $sgpr0_sgpr1 = S_LOAD_DWORDX2_IMM_ec killed renamable $sgpr4_sgpr5, 36, 0 :: (dereferenceable invariant load (s64) from %ir.out.kernarg.offset, align 4, addrspace 4)
  ; GCN-NEXT:   renamable $sgpr6 = COPY renamable $sgpr1
  ; GCN-NEXT:   renamable $sgpr0 = COPY renamable $sgpr0, implicit killed $sgpr0_sgpr1
  ; GCN-NEXT:   renamable $sgpr4 = S_MOV_B32 61440
  ; GCN-NEXT:   renamable $sgpr5 = S_MOV_B32 -1
  ; GCN-NEXT:   undef renamable $sgpr0 = COPY killed renamable $sgpr0, implicit-def $sgpr0_sgpr1_sgpr2_sgpr3
  ; GCN-NEXT:   renamable $sgpr1 = COPY killed renamable $sgpr6
  ; GCN-NEXT:   renamable $sgpr2 = COPY killed renamable $sgpr5
  ; GCN-NEXT:   renamable $sgpr3 = COPY killed renamable $sgpr4
  ; GCN-NEXT:   renamable $sgpr6 = S_MOV_B32 1
  ; GCN-NEXT:   [[V_ADD_U32_e64_:%[0-9]+]]:vgpr_32 = V_ADD_U32_e64 [[COPY]](s32), $sgpr6, 0, implicit $exec
  ; GCN-NEXT:   renamable $sgpr4_sgpr5 = V_CMP_EQ_U32_e64 [[V_ADD_U32_e64_]], $sgpr6, implicit $exec
  ; GCN-NEXT:   renamable $sgpr7 = S_MOV_B32 0
  ; GCN-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY killed renamable $sgpr7
  ; GCN-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY killed renamable $sgpr6
  ; GCN-NEXT:   [[V_CNDMASK_B32_e64_:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[COPY1]], 0, [[COPY2]], killed $sgpr4_sgpr5, implicit $exec
  ; GCN-NEXT:   renamable $sgpr6 = S_MOV_B32 2
  ; GCN-NEXT:   renamable $sgpr4_sgpr5 = V_CMP_EQ_U32_e64 [[V_ADD_U32_e64_]], $sgpr6, implicit $exec
  ; GCN-NEXT:   [[COPY3:%[0-9]+]]:vgpr_32 = COPY killed renamable $sgpr6
  ; GCN-NEXT:   [[V_CNDMASK_B32_e64_1:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[V_CNDMASK_B32_e64_]], 0, [[COPY3]], killed $sgpr4_sgpr5, implicit $exec
  ; GCN-NEXT:   renamable $sgpr6 = S_MOV_B32 3
  ; GCN-NEXT:   renamable $sgpr4_sgpr5 = V_CMP_EQ_U32_e64 [[V_ADD_U32_e64_]], $sgpr6, implicit $exec
  ; GCN-NEXT:   [[COPY4:%[0-9]+]]:vgpr_32 = COPY killed renamable $sgpr6
  ; GCN-NEXT:   [[V_CNDMASK_B32_e64_2:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[V_CNDMASK_B32_e64_1]], 0, [[COPY4]], killed $sgpr4_sgpr5, implicit $exec
  ; GCN-NEXT:   renamable $sgpr4 = S_MOV_B32 4
  ; GCN-NEXT:   renamable $sgpr6_sgpr7 = V_CMP_EQ_U32_e64 [[V_ADD_U32_e64_]], killed $sgpr4, implicit $exec
  ; GCN-NEXT:   renamable $sgpr4 = S_MOV_B32 5
  ; GCN-NEXT:   [[COPY5:%[0-9]+]]:vgpr_32 = COPY renamable $sgpr4
  ; GCN-NEXT:   [[V_CNDMASK_B32_e64_3:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[V_CNDMASK_B32_e64_2]], 0, [[COPY5]], killed $sgpr6_sgpr7, implicit $exec
  ; GCN-NEXT:   renamable $sgpr6_sgpr7 = V_CMP_EQ_U32_e64 [[V_ADD_U32_e64_]], killed $sgpr4, implicit $exec
  ; GCN-NEXT:   renamable $sgpr4 = S_MOV_B32 6
  ; GCN-NEXT:   [[COPY6:%[0-9]+]]:vgpr_32 = COPY renamable $sgpr4
  ; GCN-NEXT:   [[V_CNDMASK_B32_e64_4:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[V_CNDMASK_B32_e64_3]], 0, [[COPY6]], killed $sgpr6_sgpr7, implicit $exec
  ; GCN-NEXT:   renamable $sgpr6_sgpr7 = V_CMP_EQ_U32_e64 [[V_ADD_U32_e64_]], killed $sgpr4, implicit $exec
  ; GCN-NEXT:   renamable $sgpr4 = S_MOV_B32 7
  ; GCN-NEXT:   [[COPY7:%[0-9]+]]:vgpr_32 = COPY renamable $sgpr4
  ; GCN-NEXT:   [[V_CNDMASK_B32_e64_5:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[V_CNDMASK_B32_e64_4]], 0, [[COPY7]], killed $sgpr6_sgpr7, implicit $exec
  ; GCN-NEXT:   renamable $sgpr6_sgpr7 = V_CMP_EQ_U32_e64 [[V_ADD_U32_e64_]], killed $sgpr4, implicit $exec
  ; GCN-NEXT:   renamable $sgpr4 = S_MOV_B32 8
  ; GCN-NEXT:   [[COPY8:%[0-9]+]]:vgpr_32 = COPY renamable $sgpr4
  ; GCN-NEXT:   [[V_CNDMASK_B32_e64_6:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[V_CNDMASK_B32_e64_5]], 0, [[COPY8]], killed $sgpr6_sgpr7, implicit $exec
  ; GCN-NEXT:   renamable $sgpr6_sgpr7 = V_CMP_EQ_U32_e64 [[V_ADD_U32_e64_]], killed $sgpr4, implicit $exec
  ; GCN-NEXT:   renamable $sgpr4 = S_MOV_B32 9
  ; GCN-NEXT:   [[COPY9:%[0-9]+]]:vgpr_32 = COPY renamable $sgpr4
  ; GCN-NEXT:   [[V_CNDMASK_B32_e64_7:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[V_CNDMASK_B32_e64_6]], 0, [[COPY9]], killed $sgpr6_sgpr7, implicit $exec
  ; GCN-NEXT:   renamable $sgpr6_sgpr7 = V_CMP_EQ_U32_e64 [[V_ADD_U32_e64_]], killed $sgpr4, implicit $exec
  ; GCN-NEXT:   renamable $sgpr4 = S_MOV_B32 10
  ; GCN-NEXT:   [[COPY10:%[0-9]+]]:vgpr_32 = COPY renamable $sgpr4
  ; GCN-NEXT:   [[V_CNDMASK_B32_e64_8:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[V_CNDMASK_B32_e64_7]], 0, [[COPY10]], killed $sgpr6_sgpr7, implicit $exec
  ; GCN-NEXT:   renamable $sgpr6_sgpr7 = V_CMP_EQ_U32_e64 [[V_ADD_U32_e64_]], killed $sgpr4, implicit $exec
  ; GCN-NEXT:   renamable $sgpr4 = S_MOV_B32 11
  ; GCN-NEXT:   [[COPY11:%[0-9]+]]:vgpr_32 = COPY renamable $sgpr4
  ; GCN-NEXT:   [[V_CNDMASK_B32_e64_9:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[V_CNDMASK_B32_e64_8]], 0, [[COPY11]], killed $sgpr6_sgpr7, implicit $exec
  ; GCN-NEXT:   renamable $sgpr6_sgpr7 = V_CMP_EQ_U32_e64 [[V_ADD_U32_e64_]], killed $sgpr4, implicit $exec
  ; GCN-NEXT:   renamable $sgpr4 = S_MOV_B32 12
  ; GCN-NEXT:   [[COPY12:%[0-9]+]]:vgpr_32 = COPY renamable $sgpr4
  ; GCN-NEXT:   [[V_CNDMASK_B32_e64_10:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[V_CNDMASK_B32_e64_9]], 0, [[COPY12]], killed $sgpr6_sgpr7, implicit $exec
  ; GCN-NEXT:   renamable $sgpr6_sgpr7 = V_CMP_EQ_U32_e64 [[V_ADD_U32_e64_]], killed $sgpr4, implicit $exec
  ; GCN-NEXT:   renamable $sgpr4 = S_MOV_B32 13
  ; GCN-NEXT:   [[COPY13:%[0-9]+]]:vgpr_32 = COPY renamable $sgpr4
  ; GCN-NEXT:   [[V_CNDMASK_B32_e64_11:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[V_CNDMASK_B32_e64_10]], 0, [[COPY13]], killed $sgpr6_sgpr7, implicit $exec
  ; GCN-NEXT:   renamable $sgpr6_sgpr7 = V_CMP_EQ_U32_e64 [[V_ADD_U32_e64_]], killed $sgpr4, implicit $exec
  ; GCN-NEXT:   renamable $sgpr4 = S_MOV_B32 14
  ; GCN-NEXT:   [[COPY14:%[0-9]+]]:vgpr_32 = COPY renamable $sgpr4
  ; GCN-NEXT:   [[V_CNDMASK_B32_e64_12:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[V_CNDMASK_B32_e64_11]], 0, [[COPY14]], killed $sgpr6_sgpr7, implicit $exec
  ; GCN-NEXT:   renamable $sgpr6_sgpr7 = V_CMP_EQ_U32_e64 [[V_ADD_U32_e64_]], killed $sgpr4, implicit $exec
  ; GCN-NEXT:   renamable $sgpr4 = S_MOV_B32 15
  ; GCN-NEXT:   [[COPY15:%[0-9]+]]:vgpr_32 = COPY renamable $sgpr4
  ; GCN-NEXT:   [[V_CNDMASK_B32_e64_13:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[V_CNDMASK_B32_e64_12]], 0, [[COPY15]], killed $sgpr6_sgpr7, implicit $exec
  ; GCN-NEXT:   renamable $sgpr4_sgpr5 = V_CMP_EQ_U32_e64 [[V_ADD_U32_e64_]], killed $sgpr4, implicit $exec
  ; GCN-NEXT:   renamable $sgpr6 = S_MOV_B32 16
  ; GCN-NEXT:   [[COPY16:%[0-9]+]]:vgpr_32 = COPY killed renamable $sgpr6
  ; GCN-NEXT:   [[V_CNDMASK_B32_e64_14:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[V_CNDMASK_B32_e64_13]], 0, [[COPY16]], killed $sgpr4_sgpr5, implicit $exec
  ; GCN-NEXT:   BUFFER_STORE_DWORD_OFFSET [[V_CNDMASK_B32_e64_14]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (store (s32) into %ir.out.load, addrspace 1)
  ; GCN-NEXT:   S_ENDPGM 0
entry:
  %id = call i32 @llvm.amdgcn.workitem.id.x() #1
  %index = add i32 %id, 1
  %value = extractelement <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16>, i32 %index
  store i32 %value, ptr addrspace(1) %out
  ret void
}

