; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=sandbox-vectorizer -sbvec-passes="seed-collection(enable-diff-types)<load-store-vec>" -sbvec-collect-seeds=loads,stores -sbvec-vec-reg-bits=1024 %s -S | FileCheck %s

define i8 @vectorize_loads_general_uses(ptr %ptr) {
; CHECK-LABEL: @vectorize_loads_general_uses(
; CHECK-NEXT:    [[PTR0:%.*]] = getelementptr i8, ptr [[PTR:%.*]], i32 0
; CHECK-NEXT:    [[VECIINITL:%.*]] = load <2 x i8>, ptr [[PTR0]], align 1, !sandboxvec [[META0:![0-9]+]]
; CHECK-NEXT:    [[UNPACK:%.*]] = extractelement <2 x i8> [[VECIINITL]], i32 0, !sandboxvec [[META0]]
; CHECK-NEXT:    [[UNPACK1:%.*]] = extractelement <2 x i8> [[VECIINITL]], i32 1, !sandboxvec [[META0]]
; CHECK-NEXT:    [[SUM:%.*]] = add i8 [[UNPACK]], [[UNPACK1]]
; CHECK-NEXT:    ret i8 [[SUM]]
;
  %ptr0 = getelementptr i8, ptr %ptr, i32 0
  %ptr1 = getelementptr i8, ptr %ptr, i32 1
  %ld0 = load i8, ptr %ptr0
  %ld1 = load i8, ptr %ptr1
  %sum = add i8 %ld0, %ld1
  ret i8 %sum
}

define i8 @vectorize_loads_and_stores_seeds(ptr %ptr, ptr %dst) {
; CHECK-LABEL: @vectorize_loads_and_stores_seeds(
; CHECK-NEXT:    [[PTR0:%.*]] = getelementptr i8, ptr [[PTR:%.*]], i32 0
; CHECK-NEXT:    [[DST0:%.*]] = getelementptr i8, ptr [[DST:%.*]], i32 0
; CHECK-NEXT:    [[VECIINITL:%.*]] = load <2 x i8>, ptr [[PTR0]], align 1, !sandboxvec [[META1:![0-9]+]]
; CHECK-NEXT:    [[UNPACK:%.*]] = extractelement <2 x i8> [[VECIINITL]], i32 0, !sandboxvec [[META1]]
; CHECK-NEXT:    [[UNPACK1:%.*]] = extractelement <2 x i8> [[VECIINITL]], i32 1, !sandboxvec [[META1]]
; CHECK-NEXT:    [[SUM:%.*]] = add i8 [[UNPACK]], [[UNPACK1]]
; CHECK-NEXT:    store <2 x i8> <i8 0, i8 1>, ptr [[DST0]], align 1, !sandboxvec [[META2:![0-9]+]]
; CHECK-NEXT:    ret i8 [[SUM]]
;
  %ptr0 = getelementptr i8, ptr %ptr, i32 0
  %ptr1 = getelementptr i8, ptr %ptr, i32 1
  %dst0 = getelementptr i8, ptr %dst, i32 0
  %dst1 = getelementptr i8, ptr %dst, i32 1
  %ld0 = load i8, ptr %ptr0
  %ld1 = load i8, ptr %ptr1
  %sum = add i8 %ld0, %ld1
  store i8 0, ptr %dst0
  store i8 1, ptr %dst1
  ret i8 %sum
}

; A load with no remaining uses is dead once the vector load replaces it, and
; so is its pointer-operand GEP -- exercises tryEraseDeadLoads()'s
; hasNUses(0) branch, unlike the other tests here where every original load
; still has a use.
define i8 @vectorize_loads_dead_load(ptr %ptr) {
; CHECK-LABEL: @vectorize_loads_dead_load(
; CHECK-NEXT:    [[PTR0:%.*]] = getelementptr i8, ptr [[PTR:%.*]], i32 0
; CHECK-NEXT:    [[VECIINITL:%.*]] = load <2 x i8>, ptr [[PTR0]], align 1, !sandboxvec [[META3:![0-9]+]]
; CHECK-NEXT:    [[UNPACK:%.*]] = extractelement <2 x i8> [[VECIINITL]], i32 0, !sandboxvec [[META3]]
; CHECK-NEXT:    ret i8 [[UNPACK]]
;
  %ptr0 = getelementptr i8, ptr %ptr, i32 0
  %ptr1 = getelementptr i8, ptr %ptr, i32 1
  %ld0 = load i8, ptr %ptr0
  %ld1 = load i8, ptr %ptr1
  ret i8 %ld0
}

; A vector-typed original load must be replaced with a shuffle rather than a
; plain extractelement (see VecUtils::unpack()), unlike the scalar loads in
; the other tests here.
define <2 x i8> @vectorize_loads_vector_typed(ptr %ptr) {
; CHECK-LABEL: @vectorize_loads_vector_typed(
; CHECK-NEXT:    [[PTR0:%.*]] = getelementptr i8, ptr [[PTR:%.*]], i32 0
; CHECK-NEXT:    [[VECIINITL:%.*]] = load <4 x i8>, ptr [[PTR0]], align 1, !sandboxvec [[META4:![0-9]+]]
; CHECK-NEXT:    [[UNPACK:%.*]] = shufflevector <4 x i8> [[VECIINITL]], <4 x i8> poison, <2 x i32> <i32 0, i32 1>, !sandboxvec [[META4]]
; CHECK-NEXT:    [[UNPACK1:%.*]] = shufflevector <4 x i8> [[VECIINITL]], <4 x i8> poison, <2 x i32> <i32 2, i32 3>, !sandboxvec [[META4]]
; CHECK-NEXT:    [[SUM:%.*]] = add <2 x i8> [[UNPACK]], [[UNPACK1]]
; CHECK-NEXT:    ret <2 x i8> [[SUM]]
;
  %ptr0 = getelementptr i8, ptr %ptr, i32 0
  %ptr1 = getelementptr i8, ptr %ptr, i32 2
  %ld0 = load <2 x i8>, ptr %ptr0
  %ld1 = load <2 x i8>, ptr %ptr1
  %sum = add <2 x i8> %ld0, %ld1
  ret <2 x i8> %sum
}

define i32 @vectorize_loads_mixed_types_not_vectorized(ptr %ptr) {
; CHECK-LABEL: @vectorize_loads_mixed_types_not_vectorized(
; CHECK-NEXT:    [[PTR0:%.*]] = getelementptr i8, ptr [[PTR:%.*]], i32 0
; CHECK-NEXT:    [[PTR1:%.*]] = getelementptr i8, ptr [[PTR]], i32 4
; CHECK-NEXT:    [[LD0:%.*]] = load i32, ptr [[PTR0]], align 4
; CHECK-NEXT:    [[LD1:%.*]] = load i16, ptr [[PTR1]], align 2
; CHECK-NEXT:    [[EXT:%.*]] = zext i16 [[LD1]] to i32
; CHECK-NEXT:    [[SUM:%.*]] = add i32 [[LD0]], [[EXT]]
; CHECK-NEXT:    ret i32 [[SUM]]
;
  %ptr0 = getelementptr i8, ptr %ptr, i32 0
  %ptr1 = getelementptr i8, ptr %ptr, i32 4
  %ld0 = load i32, ptr %ptr0
  %ld1 = load i16, ptr %ptr1
  %ext = zext i16 %ld1 to i32
  %sum = add i32 %ld0, %ext
  ret i32 %sum
}
