; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=mergefunc %s | FileCheck %s

define internal void @whole_vector_store(ptr %p, <2 x i32> %value) {
; CHECK-LABEL: define internal void @whole_vector_store(
; CHECK-SAME: ptr [[P:%.*]], <2 x i32> [[VALUE:%.*]]) {
; CHECK-NEXT:    store atomic <2 x i32> [[VALUE]], ptr [[P]] monotonic, align 4
; CHECK-NEXT:    ret void
;
  store atomic <2 x i32> %value, ptr %p monotonic, align 4
  ret void
}

define internal void @elementwise_store(ptr %p, <2 x i32> %value) {
; CHECK-LABEL: define internal void @elementwise_store(
; CHECK-SAME: ptr [[P:%.*]], <2 x i32> [[VALUE:%.*]]) {
; CHECK-NEXT:    store atomic elementwise <2 x i32> [[VALUE]], ptr [[P]] monotonic, align 4
; CHECK-NEXT:    ret void
;
  store atomic elementwise <2 x i32> %value, ptr %p monotonic, align 4
  ret void
}
