//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef _LIBSYCL_DEVICE_BINARY_STRUCTURES
#define _LIBSYCL_DEVICE_BINARY_STRUCTURES

#include <cstdint>

/// Target identification strings.
///
/// A device type represented by a particular target
/// triple requires specific binary images. We need
/// to map the image type onto the device target triple.

/// Unknown target.
#define _LIBSYCL_DEVICE_BINARY_TARGET_TRIPLE_UNKNOWN "unknown-unknown-unknown"
/// SPIR-V with 64-bit pointers.
#define _LIBSYCL_DEVICE_BINARY_TARGET_SPIRV64 "spirv64-unknown-unknown"

// This is a replica of the EntryTy data structure in
// llvm/include/llvm/Frontend/Offloading/Utility.h.
struct EntryTy {
  /// Reserved bytes used to detect an older version of the struct, always zero.
  uint64_t Reserved = 0x0;
  /// The current version of the struct for runtime forward compatibility.
  uint16_t Version = 0x1;
  /// The expected consumer of this entry, e.g. SYCL or OpenMP.
  /// llvm::object::OffloadKind
  uint16_t Kind;
  /// Flags associated with the global.
  uint32_t Flags;
  /// The address of the global to be registered by the runtime.
  void *Address;
  /// The name of the symbol in the device image.
  char *SymbolName;
  /// The number of bytes the symbol takes.
  uint64_t Size;
  /// Extra generic data used to register this entry.
  uint64_t Data;
  /// An extra pointer, usually null.
  void *AuxAddr;
};

// TODO: would be nice to include it from llvm/Object. It doesn't work now since
// I have to link LLVMObject to do that (linker error otherwise).
// Copy of llvm::object::OffloadKind.
/// The producer of the associated offloading image.
enum OffloadKind : uint16_t {
  OFK_None = 0,
  OFK_OpenMP = (1 << 0),
  OFK_Cuda = (1 << 1),
  OFK_HIP = (1 << 2),
  OFK_SYCL = (1 << 3),
  OFK_LAST = (1 << 4),
};

// Copy of llvm::object::ImageKind.
/// The type of contents the offloading image contains.
enum ImageKind : uint16_t {
  IMG_None = 0,
  IMG_Object,
  IMG_Bitcode,
  IMG_Cubin,
  IMG_Fatbinary,
  IMG_PTX,
  IMG_SPIRV,
  IMG_LAST,
};

/// Device binary descriptor version supported by this library.
static const uint16_t _LIBSYCL_SUPPORTED_DEVICE_BINARY_VERSION = 3;

/// This struct is a record of the device binary information.
///  It must match the __tgt_device_image structure generated by the
///  clang-offload-wrapper tool when their `Version` field match.
struct __sycl_tgt_device_image {
  uint16_t Version;
  /// The type of offload model the binary employs. See `OffloadKind`. Only
  /// OFK_SYCL is supported by libsycl.
  uint8_t OffloadKind;
  /// Format of the binary data, see `ImageKind`.
  uint8_t ImageFormat;
  /// A null-terminated string representation of the device's target
  /// architecture. Must hold one of _LIBSYCL_DEVICE_BINARY_TARGET_* values.
  const char *TripleString;
  /// A null-terminated string; target- and compiler-specific options
  /// which are suggested to use to "compile" program at runtime.
  const char *CompileOptions;
  /// A null-terminated string; target- and compiler-specific options
  /// which are suggested to use to "link" program at runtime.
  const char *LinkOptions;
  /// Pointer to the target code start.
  const unsigned char *ImageStart;
  /// Pointer to the target code end.
  const unsigned char *ImageEnd;
  /// The offload entry table
  EntryTy *EntriesBegin;
  EntryTy *EntriesEnd;
  // TODO: properties are not supported now.
  /// Array of preperty sets.
  void *PropertiesBegin;
  void *PropertiesEnd;
};

/// Version of offload binaries descriptor `__sycl_tgt_bin_desc` supported by
/// libsycl.
static constexpr uint16_t _LIBSYCL_SUPPORTED_OFFLOAD_BINARY_VERSION = 1;

/// This struct is a record of all the device code that may be offloaded.
/// It must match the `__tgt_bin_desc` structure generated by
/// the clang-offload-wrapper tool when their `Version` field match.
struct __sycl_tgt_bin_desc {
  /// Version of the structure.
  uint16_t Version;
  /// Number of device binaries in this descriptor.
  uint16_t NumDeviceBinaries;
  /// Device binaries data.
  __sycl_tgt_device_image *DeviceImages;
  /// The offload entry table (not used, for compatibility with OpenMP).
  EntryTy *HostEntriesBegin;
  EntryTy *HostEntriesEnd;
};

#endif // _LIBSYCL_DEVICE_BINARY_STRUCTURES
