; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S  -p gvn < %s | FileCheck %s

; Check GVN does not eliminate the second call bacause of operand bundle presence.

define i32 @f(ptr %p) {
; CHECK-LABEL: define i32 @f(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    [[U:%.*]] = call i32 @g(i1 true) #[[ATTR1:[0-9]+]] [ "foo"(ptr [[P]]) ]
; CHECK-NEXT:    [[V:%.*]] = call i32 @g(i1 true) #[[ATTR1]] [ "foo"(ptr [[P]]) ]
; CHECK-NEXT:    ret i32 [[V]]
;
  %u = call i32 @g(i1 true) memory(none) ["foo"(ptr %p)]
  %v = call i32 @g(i1 true) memory(none) ["foo"(ptr %p)]
  ret i32 %v
}

declare void @g(i1) nounwind willreturn
