; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -data-layout="e-p:64:64:64-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-n8:16:32:64" -passes=gvn -S | FileCheck %s --check-prefixes=CHECK,LE
; RUN: opt < %s -data-layout="E-p:64:64:64-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-n8:16:32:64" -passes=gvn -S | FileCheck %s --check-prefixes=CHECK,BE

; A poison lane of the stored vector must not leak into lanes outside the load.

define i64 @v4i32_store_to_i64_load(ptr %p, <4 x i32> %x) {
; LE-LABEL: define i64 @v4i32_store_to_i64_load(
; LE-SAME: ptr [[P:%.*]], <4 x i32> [[X:%.*]]) {
; LE-NEXT:    store <4 x i32> [[X]], ptr [[P]], align 16
; LE-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[X]] to i128
; LE-NEXT:    [[TMP2:%.*]] = trunc i128 [[TMP1]] to i64
; LE-NEXT:    ret i64 [[TMP2]]
;
; BE-LABEL: define i64 @v4i32_store_to_i64_load(
; BE-SAME: ptr [[P:%.*]], <4 x i32> [[X:%.*]]) {
; BE-NEXT:    store <4 x i32> [[X]], ptr [[P]], align 16
; BE-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[X]] to i128
; BE-NEXT:    [[TMP2:%.*]] = lshr i128 [[TMP1]], 64
; BE-NEXT:    [[TMP3:%.*]] = trunc i128 [[TMP2]] to i64
; BE-NEXT:    ret i64 [[TMP3]]
;
  store <4 x i32> %x, ptr %p, align 16
  %v = load i64, ptr %p, align 8
  ret i64 %v
}

define i64 @v4i32_store_to_i64_load_offset(ptr %p, <4 x i32> %x) {
; CHECK-LABEL: define i64 @v4i32_store_to_i64_load_offset(
; CHECK-SAME: ptr [[P:%.*]], <4 x i32> [[X:%.*]]) {
; CHECK-NEXT:    store <4 x i32> [[X]], ptr [[P]], align 16
; CHECK-NEXT:    [[Q:%.*]] = getelementptr i8, ptr [[P]], i64 4
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[X]] to i128
; CHECK-NEXT:    [[TMP2:%.*]] = lshr i128 [[TMP1]], 32
; CHECK-NEXT:    [[TMP3:%.*]] = trunc i128 [[TMP2]] to i64
; CHECK-NEXT:    ret i64 [[TMP3]]
;
  store <4 x i32> %x, ptr %p, align 16
  %q = getelementptr i8, ptr %p, i64 4
  %v = load i64, ptr %q, align 4
  ret i64 %v
}

define i32 @v4i32_store_to_i32_load(ptr %p, <4 x i32> %x) {
; LE-LABEL: define i32 @v4i32_store_to_i32_load(
; LE-SAME: ptr [[P:%.*]], <4 x i32> [[X:%.*]]) {
; LE-NEXT:    store <4 x i32> [[X]], ptr [[P]], align 16
; LE-NEXT:    [[Q:%.*]] = getelementptr i8, ptr [[P]], i64 4
; LE-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[X]] to i128
; LE-NEXT:    [[TMP2:%.*]] = lshr i128 [[TMP1]], 32
; LE-NEXT:    [[TMP3:%.*]] = trunc i128 [[TMP2]] to i32
; LE-NEXT:    ret i32 [[TMP3]]
;
; BE-LABEL: define i32 @v4i32_store_to_i32_load(
; BE-SAME: ptr [[P:%.*]], <4 x i32> [[X:%.*]]) {
; BE-NEXT:    store <4 x i32> [[X]], ptr [[P]], align 16
; BE-NEXT:    [[Q:%.*]] = getelementptr i8, ptr [[P]], i64 4
; BE-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[X]] to i128
; BE-NEXT:    [[TMP2:%.*]] = lshr i128 [[TMP1]], 64
; BE-NEXT:    [[TMP3:%.*]] = trunc i128 [[TMP2]] to i32
; BE-NEXT:    ret i32 [[TMP3]]
;
  store <4 x i32> %x, ptr %p, align 16
  %q = getelementptr i8, ptr %p, i64 4
  %v = load i32, ptr %q, align 4
  ret i32 %v
}

define float @v4i32_store_to_float_load(ptr %p, <4 x i32> %x) {
; LE-LABEL: define float @v4i32_store_to_float_load(
; LE-SAME: ptr [[P:%.*]], <4 x i32> [[X:%.*]]) {
; LE-NEXT:    store <4 x i32> [[X]], ptr [[P]], align 16
; LE-NEXT:    [[Q:%.*]] = getelementptr i8, ptr [[P]], i64 8
; LE-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[X]] to i128
; LE-NEXT:    [[TMP2:%.*]] = lshr i128 [[TMP1]], 64
; LE-NEXT:    [[TMP3:%.*]] = trunc i128 [[TMP2]] to i32
; LE-NEXT:    [[TMP4:%.*]] = bitcast i32 [[TMP3]] to float
; LE-NEXT:    ret float [[TMP4]]
;
; BE-LABEL: define float @v4i32_store_to_float_load(
; BE-SAME: ptr [[P:%.*]], <4 x i32> [[X:%.*]]) {
; BE-NEXT:    store <4 x i32> [[X]], ptr [[P]], align 16
; BE-NEXT:    [[Q:%.*]] = getelementptr i8, ptr [[P]], i64 8
; BE-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[X]] to i128
; BE-NEXT:    [[TMP2:%.*]] = lshr i128 [[TMP1]], 32
; BE-NEXT:    [[TMP3:%.*]] = trunc i128 [[TMP2]] to i32
; BE-NEXT:    [[TMP4:%.*]] = bitcast i32 [[TMP3]] to float
; BE-NEXT:    ret float [[TMP4]]
;
  store <4 x i32> %x, ptr %p, align 16
  %q = getelementptr i8, ptr %p, i64 8
  %v = load float, ptr %q, align 4
  ret float %v
}

define <2 x i64> @v4i64_store_to_v2i64_load(ptr %p, <4 x i64> %x) {
; LE-LABEL: define <2 x i64> @v4i64_store_to_v2i64_load(
; LE-SAME: ptr [[P:%.*]], <4 x i64> [[X:%.*]]) {
; LE-NEXT:    store <4 x i64> [[X]], ptr [[P]], align 8
; LE-NEXT:    [[TMP1:%.*]] = bitcast <4 x i64> [[X]] to i256
; LE-NEXT:    [[TMP2:%.*]] = trunc i256 [[TMP1]] to i128
; LE-NEXT:    [[TMP3:%.*]] = bitcast i128 [[TMP2]] to <2 x i64>
; LE-NEXT:    ret <2 x i64> [[TMP3]]
;
; BE-LABEL: define <2 x i64> @v4i64_store_to_v2i64_load(
; BE-SAME: ptr [[P:%.*]], <4 x i64> [[X:%.*]]) {
; BE-NEXT:    store <4 x i64> [[X]], ptr [[P]], align 8
; BE-NEXT:    [[TMP1:%.*]] = bitcast <4 x i64> [[X]] to i256
; BE-NEXT:    [[TMP2:%.*]] = lshr i256 [[TMP1]], 128
; BE-NEXT:    [[TMP3:%.*]] = trunc i256 [[TMP2]] to i128
; BE-NEXT:    [[TMP4:%.*]] = bitcast i128 [[TMP3]] to <2 x i64>
; BE-NEXT:    ret <2 x i64> [[TMP4]]
;
  store <4 x i64> %x, ptr %p, align 8
  %v = load <2 x i64>, ptr %p, align 8
  ret <2 x i64> %v
}

define <2 x i16> @v4i32_store_to_v2i16_load(ptr %p, <4 x i32> %x) {
; CHECK-LABEL: define <2 x i16> @v4i32_store_to_v2i16_load(
; CHECK-SAME: ptr [[P:%.*]], <4 x i32> [[X:%.*]]) {
; CHECK-NEXT:    store <4 x i32> [[X]], ptr [[P]], align 16
; CHECK-NEXT:    [[Q:%.*]] = getelementptr i8, ptr [[P]], i64 6
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[X]] to i128
; CHECK-NEXT:    [[TMP2:%.*]] = lshr i128 [[TMP1]], 48
; CHECK-NEXT:    [[TMP3:%.*]] = trunc i128 [[TMP2]] to i32
; CHECK-NEXT:    [[TMP4:%.*]] = bitcast i32 [[TMP3]] to <2 x i16>
; CHECK-NEXT:    ret <2 x i16> [[TMP4]]
;
  store <4 x i32> %x, ptr %p, align 16
  %q = getelementptr i8, ptr %p, i64 6
  %v = load <2 x i16>, ptr %q, align 2
  ret <2 x i16> %v
}

define i64 @v2ptr_store_to_i64_load(ptr %p, <2 x ptr> %x) {
; LE-LABEL: define i64 @v2ptr_store_to_i64_load(
; LE-SAME: ptr [[P:%.*]], <2 x ptr> [[X:%.*]]) {
; LE-NEXT:    store <2 x ptr> [[X]], ptr [[P]], align 16
; LE-NEXT:    [[Q:%.*]] = getelementptr i8, ptr [[P]], i64 8
; LE-NEXT:    [[TMP1:%.*]] = ptrtoint <2 x ptr> [[X]] to <2 x i64>
; LE-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64> [[TMP1]] to i128
; LE-NEXT:    [[TMP3:%.*]] = lshr i128 [[TMP2]], 64
; LE-NEXT:    [[TMP4:%.*]] = trunc i128 [[TMP3]] to i64
; LE-NEXT:    ret i64 [[TMP4]]
;
; BE-LABEL: define i64 @v2ptr_store_to_i64_load(
; BE-SAME: ptr [[P:%.*]], <2 x ptr> [[X:%.*]]) {
; BE-NEXT:    store <2 x ptr> [[X]], ptr [[P]], align 16
; BE-NEXT:    [[Q:%.*]] = getelementptr i8, ptr [[P]], i64 8
; BE-NEXT:    [[TMP1:%.*]] = ptrtoint <2 x ptr> [[X]] to <2 x i64>
; BE-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64> [[TMP1]] to i128
; BE-NEXT:    [[TMP3:%.*]] = trunc i128 [[TMP2]] to i64
; BE-NEXT:    ret i64 [[TMP3]]
;
  store <2 x ptr> %x, ptr %p, align 16
  %q = getelementptr i8, ptr %p, i64 8
  %v = load i64, ptr %q, align 8
  ret i64 %v
}

define ptr @v2ptr_store_to_ptr_load(ptr %p, <2 x ptr> %x) {
; LE-LABEL: define ptr @v2ptr_store_to_ptr_load(
; LE-SAME: ptr [[P:%.*]], <2 x ptr> [[X:%.*]]) {
; LE-NEXT:    store <2 x ptr> [[X]], ptr [[P]], align 16
; LE-NEXT:    [[Q:%.*]] = getelementptr i8, ptr [[P]], i64 8
; LE-NEXT:    [[TMP1:%.*]] = ptrtoint <2 x ptr> [[X]] to <2 x i64>
; LE-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64> [[TMP1]] to i128
; LE-NEXT:    [[TMP3:%.*]] = lshr i128 [[TMP2]], 64
; LE-NEXT:    [[TMP4:%.*]] = trunc i128 [[TMP3]] to i64
; LE-NEXT:    [[TMP5:%.*]] = inttoptr i64 [[TMP4]] to ptr
; LE-NEXT:    ret ptr [[TMP5]]
;
; BE-LABEL: define ptr @v2ptr_store_to_ptr_load(
; BE-SAME: ptr [[P:%.*]], <2 x ptr> [[X:%.*]]) {
; BE-NEXT:    store <2 x ptr> [[X]], ptr [[P]], align 16
; BE-NEXT:    [[Q:%.*]] = getelementptr i8, ptr [[P]], i64 8
; BE-NEXT:    [[TMP1:%.*]] = ptrtoint <2 x ptr> [[X]] to <2 x i64>
; BE-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64> [[TMP1]] to i128
; BE-NEXT:    [[TMP3:%.*]] = trunc i128 [[TMP2]] to i64
; BE-NEXT:    [[TMP4:%.*]] = inttoptr i64 [[TMP3]] to ptr
; BE-NEXT:    ret ptr [[TMP4]]
;
  store <2 x ptr> %x, ptr %p, align 16
  %q = getelementptr i8, ptr %p, i64 8
  %v = load ptr, ptr %q, align 8
  ret ptr %v
}

define i64 @v4i32_load_to_i64_load(ptr %p) {
; LE-LABEL: define i64 @v4i32_load_to_i64_load(
; LE-SAME: ptr [[P:%.*]]) {
; LE-NEXT:    [[A:%.*]] = load <4 x i32>, ptr [[P]], align 16
; LE-NEXT:    [[Q:%.*]] = getelementptr i8, ptr [[P]], i64 8
; LE-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[A]] to i128
; LE-NEXT:    [[TMP2:%.*]] = lshr i128 [[TMP1]], 64
; LE-NEXT:    [[TMP3:%.*]] = trunc i128 [[TMP2]] to i64
; LE-NEXT:    call void @use(<4 x i32> [[A]])
; LE-NEXT:    ret i64 [[TMP3]]
;
; BE-LABEL: define i64 @v4i32_load_to_i64_load(
; BE-SAME: ptr [[P:%.*]]) {
; BE-NEXT:    [[A:%.*]] = load <4 x i32>, ptr [[P]], align 16
; BE-NEXT:    [[Q:%.*]] = getelementptr i8, ptr [[P]], i64 8
; BE-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[A]] to i128
; BE-NEXT:    [[TMP2:%.*]] = trunc i128 [[TMP1]] to i64
; BE-NEXT:    call void @use(<4 x i32> [[A]])
; BE-NEXT:    ret i64 [[TMP2]]
;
  %a = load <4 x i32>, ptr %p, align 16
  %q = getelementptr i8, ptr %p, i64 8
  %b = load i64, ptr %q, align 8
  call void @use(<4 x i32> %a)
  ret i64 %b
}

; Reduced from https://github.com/llvm/llvm-project/issues/99268.
define i64 @v4i32_load_to_i64_load_pre(ptr %p, i1 %c) {
; LE-LABEL: define i64 @v4i32_load_to_i64_load_pre(
; LE-SAME: ptr [[P:%.*]], i1 [[C:%.*]]) {
; LE-NEXT:  [[ENTRY:.*:]]
; LE-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[ELSE:.*]]
; LE:       [[THEN]]:
; LE-NEXT:    [[A:%.*]] = load <4 x i32>, ptr [[P]], align 16
; LE-NEXT:    call void @use(<4 x i32> [[A]])
; LE-NEXT:    [[TMP0:%.*]] = bitcast <4 x i32> [[A]] to i128
; LE-NEXT:    [[TMP1:%.*]] = trunc i128 [[TMP0]] to i64
; LE-NEXT:    br label %[[EXIT:.*]]
; LE:       [[ELSE]]:
; LE-NEXT:    [[B_PRE:%.*]] = load i64, ptr [[P]], align 8
; LE-NEXT:    br label %[[EXIT]]
; LE:       [[EXIT]]:
; LE-NEXT:    [[B:%.*]] = phi i64 [ [[B_PRE]], %[[ELSE]] ], [ [[TMP1]], %[[THEN]] ]
; LE-NEXT:    ret i64 [[B]]
;
; BE-LABEL: define i64 @v4i32_load_to_i64_load_pre(
; BE-SAME: ptr [[P:%.*]], i1 [[C:%.*]]) {
; BE-NEXT:  [[ENTRY:.*:]]
; BE-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[ELSE:.*]]
; BE:       [[THEN]]:
; BE-NEXT:    [[A:%.*]] = load <4 x i32>, ptr [[P]], align 16
; BE-NEXT:    call void @use(<4 x i32> [[A]])
; BE-NEXT:    [[TMP0:%.*]] = bitcast <4 x i32> [[A]] to i128
; BE-NEXT:    [[TMP1:%.*]] = lshr i128 [[TMP0]], 64
; BE-NEXT:    [[TMP2:%.*]] = trunc i128 [[TMP1]] to i64
; BE-NEXT:    br label %[[EXIT:.*]]
; BE:       [[ELSE]]:
; BE-NEXT:    [[B_PRE:%.*]] = load i64, ptr [[P]], align 8
; BE-NEXT:    br label %[[EXIT]]
; BE:       [[EXIT]]:
; BE-NEXT:    [[B:%.*]] = phi i64 [ [[B_PRE]], %[[ELSE]] ], [ [[TMP2]], %[[THEN]] ]
; BE-NEXT:    ret i64 [[B]]
;
entry:
  br i1 %c, label %then, label %else

then:
  %a = load <4 x i32>, ptr %p, align 16
  call void @use(<4 x i32> %a)
  br label %exit

else:
  br label %exit

exit:
  %b = load i64, ptr %p, align 8
  ret i64 %b
}

; A scalar load of the whole vector is poison if any lane is.
define i128 @v4i32_store_to_i128_load(ptr %p, <4 x i32> %x) {
; CHECK-LABEL: define i128 @v4i32_store_to_i128_load(
; CHECK-SAME: ptr [[P:%.*]], <4 x i32> [[X:%.*]]) {
; CHECK-NEXT:    store <4 x i32> [[X]], ptr [[P]], align 16
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[X]] to i128
; CHECK-NEXT:    ret i128 [[TMP1]]
;
  store <4 x i32> %x, ptr %p, align 16
  %v = load i128, ptr %p, align 16
  ret i128 %v
}

define <2 x i64> @v4i32_store_to_v2i64_load(ptr %p, <4 x i32> %x) {
; CHECK-LABEL: define <2 x i64> @v4i32_store_to_v2i64_load(
; CHECK-SAME: ptr [[P:%.*]], <4 x i32> [[X:%.*]]) {
; CHECK-NEXT:    store <4 x i32> [[X]], ptr [[P]], align 16
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[X]] to i128
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast i128 [[TMP1]] to <2 x i64>
; CHECK-NEXT:    ret <2 x i64> [[TMP2]]
;
  store <4 x i32> %x, ptr %p, align 16
  %v = load <2 x i64>, ptr %p, align 16
  ret <2 x i64> %v
}

define <4 x i32> @v2ptr_store_to_v4i32_load(ptr %p, <2 x ptr> %x) {
; CHECK-LABEL: define <4 x i32> @v2ptr_store_to_v4i32_load(
; CHECK-SAME: ptr [[P:%.*]], <2 x ptr> [[X:%.*]]) {
; CHECK-NEXT:    store <2 x ptr> [[X]], ptr [[P]], align 16
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint <2 x ptr> [[X]] to <2 x i64>
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64> [[TMP1]] to i128
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast i128 [[TMP2]] to <4 x i32>
; CHECK-NEXT:    ret <4 x i32> [[TMP3]]
;
  store <2 x ptr> %x, ptr %p, align 16
  %v = load <4 x i32>, ptr %p, align 16
  ret <4 x i32> %v
}

; Constant folding keeps poison per lane.
define i64 @v4i32_const_store_to_i64_load(ptr %p) {
; LE-LABEL: define i64 @v4i32_const_store_to_i64_load(
; LE-SAME: ptr [[P:%.*]]) {
; LE-NEXT:    store <4 x i32> <i32 1, i32 2, i32 poison, i32 4>, ptr [[P]], align 16
; LE-NEXT:    ret i64 8589934593
;
; BE-LABEL: define i64 @v4i32_const_store_to_i64_load(
; BE-SAME: ptr [[P:%.*]]) {
; BE-NEXT:    store <4 x i32> <i32 1, i32 2, i32 poison, i32 4>, ptr [[P]], align 16
; BE-NEXT:    [[TMP1:%.*]] = lshr i128 bitcast (<4 x i32> <i32 1, i32 2, i32 poison, i32 4> to i128), 64
; BE-NEXT:    [[TMP2:%.*]] = trunc i128 [[TMP1]] to i64
; BE-NEXT:    ret i64 [[TMP2]]
;
  store <4 x i32> <i32 1, i32 2, i32 poison, i32 4>, ptr %p, align 16
  %v = load i64, ptr %p, align 8
  ret i64 %v
}

declare void @use(<4 x i32>) memory(none)
