; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu -slp-threshold=-1000 < %s | FileCheck %s

define i64 @test(ptr %buf) {
; CHECK-LABEL: define i64 @test(
; CHECK-SAME: ptr [[BUF:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[BUF]], align 1
; CHECK-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds nuw i8, ptr [[BUF]], i64 1
; CHECK-NEXT:    [[TMP8:%.*]] = load i8, ptr [[ARRAYIDX1]], align 1
; CHECK-NEXT:    [[ARRAYIDX22:%.*]] = getelementptr inbounds nuw i8, ptr [[BUF]], i64 2
; CHECK-NEXT:    [[TMP10:%.*]] = load i8, ptr [[ARRAYIDX22]], align 1
; CHECK-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds nuw i8, ptr [[BUF]], i64 3
; CHECK-NEXT:    [[TMP3:%.*]] = zext i8 [[TMP0]] to i32
; CHECK-NEXT:    [[TMP4:%.*]] = insertelement <5 x i32> <i32 poison, i32 1, i32 1, i32 1, i32 1>, i32 [[TMP3]], i64 0
; CHECK-NEXT:    [[TMP5:%.*]] = mul <5 x i32> <i32 24, i32 0, i32 0, i32 0, i32 0>, [[TMP4]]
; CHECK-NEXT:    [[TMP17:%.*]] = zext i8 [[TMP8]] to i32
; CHECK-NEXT:    [[TMP7:%.*]] = insertelement <5 x i32> <i32 poison, i32 1, i32 1, i32 1, i32 1>, i32 [[TMP17]], i64 0
; CHECK-NEXT:    [[TMP19:%.*]] = mul <5 x i32> <i32 16, i32 0, i32 0, i32 0, i32 0>, [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = or disjoint <5 x i32> [[TMP19]], [[TMP5]]
; CHECK-NEXT:    [[TMP21:%.*]] = zext i8 [[TMP10]] to i32
; CHECK-NEXT:    [[TMP11:%.*]] = insertelement <5 x i32> <i32 poison, i32 1, i32 1, i32 1, i32 1>, i32 [[TMP21]], i64 0
; CHECK-NEXT:    [[TMP12:%.*]] = mul <5 x i32> <i32 8, i32 0, i32 0, i32 0, i32 0>, [[TMP11]]
; CHECK-NEXT:    [[TMP13:%.*]] = or disjoint <5 x i32> [[TMP9]], [[TMP12]]
; CHECK-NEXT:    [[TMP14:%.*]] = load <5 x i8>, ptr [[ARRAYIDX8]], align 1
; CHECK-NEXT:    [[TMP15:%.*]] = zext <5 x i8> [[TMP14]] to <5 x i32>
; CHECK-NEXT:    [[TMP16:%.*]] = or disjoint <5 x i32> [[TMP13]], [[TMP15]]
; CHECK-NEXT:    [[TMP20:%.*]] = mul <5 x i32> [[TMP16]], <i32 32, i32 24, i32 16, i32 8, i32 1>
; CHECK-NEXT:    [[TMP18:%.*]] = zext <5 x i32> [[TMP20]] to <5 x i64>
; CHECK-NEXT:    [[OP_RDX:%.*]] = call i64 @llvm.vector.reduce.or.v5i64(<5 x i64> [[TMP18]])
; CHECK-NEXT:    ret i64 [[OP_RDX]]
;
entry:
  %0 = load i8, ptr %buf, align 1
  %conv = zext i8 %0 to i64
  %mul = mul i64 %conv, 24
  %arrayidx1 = getelementptr inbounds nuw i8, ptr %buf, i64 1
  %1 = load i8, ptr %arrayidx1, align 1
  %conv2 = zext i8 %1 to i64
  %mul3 = mul i64 %conv2, 16
  %or = or disjoint i64 %mul3, %mul
  %arrayidx4 = getelementptr inbounds nuw i8, ptr %buf, i64 2
  %2 = load i8, ptr %arrayidx4, align 1
  %conv5 = zext i8 %2 to i64
  %mul6 = mul i64 %conv5, 8
  %or7 = or disjoint i64 %or, %mul6
  %arrayidx8 = getelementptr inbounds nuw i8, ptr %buf, i64 3
  %3 = load i8, ptr %arrayidx8, align 1
  %conv9 = zext i8 %3 to i64
  %or10 = or disjoint i64 %or7, %conv9
  %mul12 = mul i64 %or10, 32
  %add.ptr = getelementptr inbounds nuw i8, ptr %buf, i64 4
  %4 = load i8, ptr %add.ptr, align 1
  %conv14 = zext i8 %4 to i64
  %mul15 = mul i64 %conv14, 24
  %arrayidx17 = getelementptr inbounds nuw i8, ptr %buf, i64 5
  %5 = load i8, ptr %arrayidx17, align 1
  %conv18 = zext i8 %5 to i64
  %mul19 = mul i64 %conv18, 16
  %or20 = or disjoint i64 %mul19, %mul15
  %arrayidx22 = getelementptr inbounds nuw i8, ptr %buf, i64 6
  %6 = load i8, ptr %arrayidx22, align 1
  %conv23 = zext i8 %6 to i64
  %mul24 = mul i64 %conv23, 8
  %arrayidx27 = getelementptr inbounds nuw i8, ptr %buf, i64 7
  %7 = load i8, ptr %arrayidx27, align 1
  %conv28 = zext i8 %7 to i64
  %or25 = or disjoint i64 %or20, %mul12
  %or29 = or disjoint i64 %or25, %mul24
  %add = or disjoint i64 %or29, %conv28
  ret i64 %add
}
