; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S --passes=slp-vectorizer -S -mtriple=i686-unknown-linux-android29 -mattr=+sse2 < %s | FileCheck %s

define void @test(ptr %0, i64 %1, i64 %2, i1 %3, i64 %4, i64 %5) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: ptr [[TMP0:%.*]], i64 [[TMP1:%.*]], i64 [[TMP2:%.*]], i1 [[TMP3:%.*]], i64 [[TMP4:%.*]], i64 [[TMP5:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr [[TMP0]], i32 248
; CHECK-NEXT:    [[TMP8:%.*]] = load i64, ptr [[TMP9]], align 4
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[TMP0]], i32 240
; CHECK-NEXT:    [[TMP10:%.*]] = load i64, ptr [[TMP7]], align 4
; CHECK-NEXT:    [[TMP14:%.*]] = load i64, ptr null, align 4
; CHECK-NEXT:    [[TMP12:%.*]] = add i64 [[TMP1]], 1
; CHECK-NEXT:    [[TMP13:%.*]] = add i64 [[TMP1]], 1
; CHECK-NEXT:    [[TMP33:%.*]] = add i64 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr i8, ptr [[TMP0]], i32 136
; CHECK-NEXT:    [[TMP16:%.*]] = load i64, ptr [[TMP15]], align 4
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr i8, ptr [[TMP0]], i32 128
; CHECK-NEXT:    [[TMP18:%.*]] = load i64, ptr [[TMP17]], align 4
; CHECK-NEXT:    [[TMP19:%.*]] = add i64 [[TMP18]], [[TMP1]]
; CHECK-NEXT:    [[TMP20:%.*]] = sub i64 0, [[TMP18]]
; CHECK-NEXT:    [[TMP27:%.*]] = sub i64 0, [[TMP8]]
; CHECK-NEXT:    [[TMP28:%.*]] = sub i64 0, [[TMP19]]
; CHECK-NEXT:    [[TMP23:%.*]] = insertelement <6 x i64> <i64 0, i64 poison, i64 0, i64 0, i64 0, i64 0>, i64 [[TMP1]], i32 1
; CHECK-NEXT:    [[TMP24:%.*]] = shufflevector <6 x i64> [[TMP23]], <6 x i64> <i64 poison, i64 -1, i64 poison, i64 poison, i64 poison, i64 poison>, <6 x i32> <i32 1, i32 7, i32 1, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP25:%.*]] = insertelement <6 x i64> [[TMP24]], i64 [[TMP14]], i32 3
; CHECK-NEXT:    [[TMP26:%.*]] = insertelement <6 x i64> [[TMP25]], i64 [[TMP16]], i32 4
; CHECK-NEXT:    [[TMP46:%.*]] = insertelement <6 x i64> [[TMP26]], i64 [[TMP10]], i32 5
; CHECK-NEXT:    [[TMP47:%.*]] = sub <6 x i64> [[TMP23]], [[TMP46]]
; CHECK-NEXT:    [[TMP29:%.*]] = shufflevector <6 x i64> [[TMP46]], <6 x i64> poison, <2 x i32> <i32 3, i32 3>
; CHECK-NEXT:    [[TMP30:%.*]] = add <2 x i64> [[TMP29]], splat (i64 1)
; CHECK-NEXT:    [[TMP31:%.*]] = ashr <2 x i64> [[TMP30]], splat (i64 14)
; CHECK-NEXT:    [[TMP32:%.*]] = shufflevector <6 x i64> [[TMP47]], <6 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP57:%.*]] = shufflevector <2 x i64> [[TMP31]], <2 x i64> poison, <8 x i32> <i32 0, i32 1, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP58:%.*]] = shufflevector <8 x i64> [[TMP32]], <8 x i64> [[TMP57]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 8, i32 9>
; CHECK-NEXT:    br i1 [[TMP3]], label %[[BB52:.*]], label %[[BB37:.*]]
; CHECK:       [[BB37]]:
; CHECK-NEXT:    [[TMP34:%.*]] = ashr i64 [[TMP2]], 2
; CHECK-NEXT:    [[TMP35:%.*]] = ashr i64 [[TMP1]], 2
; CHECK-NEXT:    [[TMP36:%.*]] = add i64 [[TMP1]], 1
; CHECK-NEXT:    [[TMP37:%.*]] = ashr i64 [[TMP36]], 2
; CHECK-NEXT:    [[TMP38:%.*]] = add i64 [[TMP1]], 1
; CHECK-NEXT:    [[TMP39:%.*]] = lshr i64 [[TMP1]], 1
; CHECK-NEXT:    [[TMP40:%.*]] = add i64 [[TMP38]], [[TMP39]]
; CHECK-NEXT:    [[TMP41:%.*]] = ashr i64 [[TMP40]], 2
; CHECK-NEXT:    [[TMP42:%.*]] = add i64 [[TMP1]], 1
; CHECK-NEXT:    [[TMP43:%.*]] = lshr i64 [[TMP1]], 1
; CHECK-NEXT:    [[TMP44:%.*]] = add i64 [[TMP42]], [[TMP43]]
; CHECK-NEXT:    [[TMP45:%.*]] = ashr i64 [[TMP44]], 2
; CHECK-NEXT:    [[TMP48:%.*]] = shufflevector <6 x i64> [[TMP23]], <6 x i64> poison, <2 x i32> <i32 1, i32 1>
; CHECK-NEXT:    [[TMP49:%.*]] = add <2 x i64> [[TMP48]], splat (i64 1)
; CHECK-NEXT:    [[TMP50:%.*]] = shufflevector <2 x i64> [[TMP48]], <2 x i64> poison, <8 x i32> <i32 0, i32 0, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 0>
; CHECK-NEXT:    [[TMP51:%.*]] = insertelement <8 x i64> [[TMP50]], i64 [[TMP4]], i32 3
; CHECK-NEXT:    [[TMP52:%.*]] = insertelement <8 x i64> [[TMP51]], i64 [[TMP5]], i32 4
; CHECK-NEXT:    [[TMP53:%.*]] = shufflevector <2 x i64> [[TMP49]], <2 x i64> poison, <8 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1>
; CHECK-NEXT:    [[TMP54:%.*]] = shufflevector <2 x i64> [[TMP49]], <2 x i64> poison, <8 x i32> <i32 0, i32 1, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP55:%.*]] = shufflevector <8 x i64> [[TMP54]], <8 x i64> [[TMP52]], <8 x i32> <i32 8, i32 9, i32 0, i32 11, i32 12, i32 1, i32 14, i32 15>
; CHECK-NEXT:    [[TMP56:%.*]] = ashr <8 x i64> [[TMP55]], splat (i64 2)
; CHECK-NEXT:    [[TMP80:%.*]] = add i64 [[TMP1]], 1
; CHECK-NEXT:    [[TMP81:%.*]] = ashr i64 [[TMP80]], 2
; CHECK-NEXT:    br label %[[BB52]]
; CHECK:       [[BB52]]:
; CHECK-NEXT:    [[TMP77:%.*]] = phi i64 [ [[TMP81]], %[[BB37]] ], [ [[TMP27]], [[TMP6:%.*]] ]
; CHECK-NEXT:    [[TMP61:%.*]] = phi i64 [ [[TMP45]], %[[BB37]] ], [ [[TMP20]], [[TMP6]] ]
; CHECK-NEXT:    [[TMP76:%.*]] = phi i64 [ [[TMP41]], %[[BB37]] ], [ [[TMP28]], [[TMP6]] ]
; CHECK-NEXT:    [[TMP71:%.*]] = phi i64 [ [[TMP34]], %[[BB37]] ], [ [[TMP12]], [[TMP6]] ]
; CHECK-NEXT:    [[TMP70:%.*]] = phi i64 [ [[TMP35]], %[[BB37]] ], [ [[TMP13]], [[TMP6]] ]
; CHECK-NEXT:    [[TMP63:%.*]] = phi i64 [ [[TMP37]], %[[BB37]] ], [ [[TMP33]], [[TMP6]] ]
; CHECK-NEXT:    [[TMP66:%.*]] = phi <8 x i64> [ [[TMP56]], %[[BB37]] ], [ [[TMP58]], [[TMP6]] ]
; CHECK-NEXT:    [[TMP72:%.*]] = or i64 [[TMP71]], [[TMP70]]
; CHECK-NEXT:    [[TMP73:%.*]] = or i64 [[TMP63]], [[TMP72]]
; CHECK-NEXT:    [[TMP69:%.*]] = call i64 @llvm.vector.reduce.or.v8i64(<8 x i64> [[TMP66]])
; CHECK-NEXT:    [[TMP75:%.*]] = or i64 [[TMP69]], [[TMP61]]
; CHECK-NEXT:    store i64 [[TMP73]], ptr [[TMP0]], align 4
; CHECK-NEXT:    store i64 [[TMP76]], ptr null, align 4
; CHECK-NEXT:    store i64 [[TMP77]], ptr [[TMP0]], align 4
; CHECK-NEXT:    store i64 [[TMP75]], ptr null, align 4
; CHECK-NEXT:    ret void
;
  %7 = getelementptr i8, ptr %0, i32 248
  %8 = load i64, ptr %7, align 4
  %9 = getelementptr i8, ptr %0, i32 240
  %10 = load i64, ptr %9, align 4
  %11 = load i64, ptr null, align 4
  %12 = add i64 %1, 1
  %13 = add i64 %1, 1
  %14 = add i64 %1, %2
  %15 = getelementptr i8, ptr %0, i32 136
  %16 = load i64, ptr %15, align 4
  %17 = getelementptr i8, ptr %0, i32 128
  %18 = load i64, ptr %17, align 4
  %19 = add i64 %18, %1
  %20 = sub i64 0, %18
  %21 = sub i64 0, %16
  %22 = sub i64 0, %11
  %23 = add i64 %1, 1
  %24 = sub i64 0, %1
  %25 = sub i64 0, %1
  %26 = sub i64 0, %10
  %27 = sub i64 0, %8
  %28 = sub i64 0, %19
  %29 = add i64 %11, 1
  %30 = ashr i64 %29, 14
  %31 = add i64 %11, 1
  %32 = ashr i64 %31, 14
  br i1 %3, label %58, label %33

33:
  %34 = ashr i64 %2, 2
  %35 = ashr i64 %1, 2
  %36 = add i64 %1, 1
  %37 = ashr i64 %36, 2
  %38 = add i64 %1, 1
  %39 = lshr i64 %1, 1
  %40 = add i64 %38, %39
  %41 = ashr i64 %40, 2
  %42 = add i64 %1, 1
  %43 = lshr i64 %1, 1
  %44 = add i64 %42, %43
  %45 = ashr i64 %44, 2
  %46 = ashr i64 %5, 2
  %47 = ashr i64 %4, 2
  %48 = ashr i64 %1, 2
  %49 = ashr i64 %1, 2
  %50 = ashr i64 %1, 2
  %51 = ashr i64 %1, 2
  %52 = add i64 %1, 1
  %53 = ashr i64 %52, 2
  %54 = add i64 %1, 1
  %55 = ashr i64 %54, 2
  %56 = add i64 %1, 1
  %57 = ashr i64 %56, 2
  br label %58

58:
  %59 = phi i64 [ %51, %33 ], [ %24, %6 ]
  %60 = phi i64 [ %50, %33 ], [ %32, %6 ]
  %61 = phi i64 [ %53, %33 ], [ %25, %6 ]
  %62 = phi i64 [ %55, %33 ], [ %26, %6 ]
  %63 = phi i64 [ %57, %33 ], [ %27, %6 ]
  %64 = phi i64 [ %49, %33 ], [ %30, %6 ]
  %65 = phi i64 [ %48, %33 ], [ %23, %6 ]
  %66 = phi i64 [ %47, %33 ], [ %22, %6 ]
  %67 = phi i64 [ %46, %33 ], [ %21, %6 ]
  %68 = phi i64 [ %45, %33 ], [ %20, %6 ]
  %69 = phi i64 [ %41, %33 ], [ %28, %6 ]
  %70 = phi i64 [ %34, %33 ], [ %12, %6 ]
  %71 = phi i64 [ %35, %33 ], [ %13, %6 ]
  %72 = phi i64 [ %37, %33 ], [ %14, %6 ]
  %73 = or i64 %65, %64
  %74 = or i64 %59, %60
  %75 = or i64 %70, %71
  %76 = or i64 %74, %73
  %77 = or i64 %61, %66
  %78 = or i64 %72, %75
  %79 = or i64 %67, %77
  %80 = or i64 %62, %79
  %81 = or i64 %76, %80
  %82 = or i64 %68, %81
  store i64 %78, ptr %0, align 4
  store i64 %69, ptr null, align 4
  store i64 %63, ptr %0, align 4
  store i64 %82, ptr null, align 4
  ret void
}

