; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV32 %s
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+experimental-zilx -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV32-ZILX %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV64 %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+experimental-zilx -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV64-ZILX %s

;------------------------------------------------------------------------------
; Unscaled Load
;------------------------------------------------------------------------------

define i8 @lxb_anyext(ptr %a, iXLen %b) {
; RV32-LABEL: lxb_anyext:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lbu a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxb_anyext:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxb a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxb_anyext:
; RV64:       # %bb.0:
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lbu a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxb_anyext:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxb a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = getelementptr i8, ptr %a, iXLen %b
  %2 = load i8, ptr %1, align 1
  ret i8 %2
}

define i32 @lxb(ptr %a, iXLen %b) {
; RV32-LABEL: lxb:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lb a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxb:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxb a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxb:
; RV64:       # %bb.0:
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lb a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxb:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxb a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = getelementptr i8, ptr %a, iXLen %b
  %2 = load i8, ptr %1, align 1
  %3 = sext i8 %2 to i32
  ret i32 %3
}

define i8 @lxb_uw_anyext(ptr %a, i32 %b) {
; RV32-LABEL: lxb_uw_anyext:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lbu a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxb_uw_anyext:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxb a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxb_uw_anyext:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 32
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lbu a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxb_uw_anyext:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxb.uw a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = zext i32 %b to i64
  %2 = getelementptr i8, ptr %a, i64 %1
  %3 = load i8, ptr %2, align 1
  ret i8 %3
}

define i32 @lxb_uw(ptr %a, i32 %b) {
; RV32-LABEL: lxb_uw:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lb a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxb_uw:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxb a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxb_uw:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 32
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lb a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxb_uw:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxb.uw a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = zext i32 %b to i64
  %2 = getelementptr i8, ptr %a, i64 %1
  %3 = load i8, ptr %2, align 1
  %4 = sext i8 %3 to i32
  ret i32 %4
}

define i32 @lxbu(ptr %a, iXLen %b) {
; RV32-LABEL: lxbu:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lbu a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxbu:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxbu a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxbu:
; RV64:       # %bb.0:
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lbu a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxbu:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxbu a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = getelementptr i8, ptr %a, iXLen %b
  %2 = load i8, ptr %1, align 1
  %3 = zext i8 %2 to i32
  ret i32 %3
}

define i32 @lxbu_uw(ptr %a, i32 %b) {
; RV32-LABEL: lxbu_uw:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lbu a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxbu_uw:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxbu a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxbu_uw:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 32
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lbu a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxbu_uw:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxbu.uw a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = zext i32 %b to i64
  %2 = getelementptr i8, ptr %a, i64 %1
  %3 = load i8, ptr %2, align 1
  %4 = zext i8 %3 to i32
  ret i32 %4
}

define i16 @lxh(ptr %a, iXLen %b) {
; RV32-LABEL: lxh:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lh a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxh:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxh a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxh:
; RV64:       # %bb.0:
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lh a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxh:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxh a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = getelementptr i8, ptr %a, iXLen %b
  %2 = load i16, ptr %1, align 2
  ret i16 %2
}

define i16 @lxh_uw(ptr %a, i32 %b) {
; RV32-LABEL: lxh_uw:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lh a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxh_uw:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxh a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxh_uw:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 32
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lh a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxh_uw:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxh.uw a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = zext i32 %b to i64
  %2 = getelementptr i8, ptr %a, i64 %1
  %3 = load i16, ptr %2, align 2
  ret i16 %3
}

define i32 @lxhu(ptr %a, iXLen %b) {
; RV32-LABEL: lxhu:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lhu a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxhu:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxhu a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxhu:
; RV64:       # %bb.0:
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lhu a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxhu:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxhu a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = getelementptr i8, ptr %a, iXLen %b
  %2 = load i16, ptr %1, align 2
  %3 = zext i16 %2 to i32
  ret i32 %3
}

define i32 @lxhu_uw(ptr %a, i32 %b) {
; RV32-LABEL: lxhu_uw:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lhu a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxhu_uw:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxhu a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxhu_uw:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 32
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lhu a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxhu_uw:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxhu.uw a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = zext i32 %b to i64
  %2 = getelementptr i8, ptr %a, i64 %1
  %3 = load i16, ptr %2, align 2
  %4 = zext i16 %3 to i32
  ret i32 %4
}

define i32 @lxw(ptr %a, iXLen %b) {
; RV32-LABEL: lxw:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lw a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxw:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxw a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxw:
; RV64:       # %bb.0:
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lw a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxw:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxw a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = getelementptr i8, ptr %a, iXLen %b
  %2 = load i32, ptr %1, align 4
  ret i32 %2
}

define i32 @lxw_uw(ptr %a, i32 %b) {
; RV32-LABEL: lxw_uw:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lw a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxw_uw:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxw a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxw_uw:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 32
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lw a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxw_uw:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxw.uw a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = zext i32 %b to i64
  %2 = getelementptr i8, ptr %a, i64 %1
  %3 = load i32, ptr %2, align 4
  ret i32 %3
}

define i64 @lxwu(ptr %a, iXLen %b) {
; RV32-LABEL: lxwu:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lw a0, 0(a0)
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxwu:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxw a0, (a0), a1
; RV32-ZILX-NEXT:    li a1, 0
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxwu:
; RV64:       # %bb.0:
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lwu a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxwu:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxwu a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = getelementptr i8, ptr %a, iXLen %b
  %2 = load i32, ptr %1, align 4
  %3 = zext i32 %2 to i64
  ret i64 %3
}

define i64 @lxwu_uw(ptr %a, i32 %b) {
; RV32-LABEL: lxwu_uw:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lw a0, 0(a0)
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxwu_uw:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxw a0, (a0), a1
; RV32-ZILX-NEXT:    li a1, 0
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxwu_uw:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 32
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lwu a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxwu_uw:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxwu.uw a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = zext i32 %b to i64
  %2 = getelementptr i8, ptr %a, i64 %1
  %3 = load i32, ptr %2, align 4
  %4 = zext i32 %3 to i64
  ret i64 %4
}

define i64 @lxd(ptr %a, iXLen %b) {
; RV32-LABEL: lxd:
; RV32:       # %bb.0:
; RV32-NEXT:    add a1, a0, a1
; RV32-NEXT:    lw a0, 0(a1)
; RV32-NEXT:    lw a1, 4(a1)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxd:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    add a1, a0, a1
; RV32-ZILX-NEXT:    lw a0, 0(a1)
; RV32-ZILX-NEXT:    lw a1, 4(a1)
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxd:
; RV64:       # %bb.0:
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    ld a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxd:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxd a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = getelementptr i8, ptr %a, iXLen %b
  %2 = load i64, ptr %1, align 8
  ret i64 %2
}

define i64 @lxd_uw(ptr %a, i32 %b) {
; RV32-LABEL: lxd_uw:
; RV32:       # %bb.0:
; RV32-NEXT:    add a1, a0, a1
; RV32-NEXT:    lw a0, 0(a1)
; RV32-NEXT:    lw a1, 4(a1)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxd_uw:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    add a1, a0, a1
; RV32-ZILX-NEXT:    lw a0, 0(a1)
; RV32-ZILX-NEXT:    lw a1, 4(a1)
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxd_uw:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 32
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    ld a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxd_uw:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxd.uw a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = zext i32 %b to i64
  %2 = getelementptr i8, ptr %a, i64 %1
  %3 = load i64, ptr %2, align 8
  ret i64 %3
}

;------------------------------------------------------------------------------
; Scaled Load
;------------------------------------------------------------------------------

define i16 @lxh_s_anyext(ptr %a, iXLen %b) {
; RV32-LABEL: lxh_s_anyext:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 1
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lh a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxh_s_anyext:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxh.s a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxh_s_anyext:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 1
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lh a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxh_s_anyext:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxh.s a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = getelementptr i16, ptr %a, iXLen %b
  %2 = load i16, ptr %1, align 2
  ret i16 %2
}

define i32 @lxh_s(ptr %a, iXLen %b) {
; RV32-LABEL: lxh_s:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 1
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lh a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxh_s:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxh.s a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxh_s:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 1
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lh a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxh_s:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxh.s a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = getelementptr i16, ptr %a, iXLen %b
  %2 = load i16, ptr %1, align 2
  %3 = sext i16 %2 to i32
  ret i32 %3
}

define i16 @lxh_s_uw_anyext(ptr %a, i32 %b) {
; RV32-LABEL: lxh_s_uw_anyext:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 1
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lh a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxh_s_uw_anyext:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxh.s a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxh_s_uw_anyext:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 31
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lh a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxh_s_uw_anyext:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxh.s.uw a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = zext i32 %b to i64
  %2 = getelementptr i16, ptr %a, i64 %1
  %3 = load i16, ptr %2, align 2
  ret i16 %3
}

define i32 @lxh_s_uw(ptr %a, i32 %b) {
; RV32-LABEL: lxh_s_uw:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 1
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lh a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxh_s_uw:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxh.s a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxh_s_uw:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 31
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lh a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxh_s_uw:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxh.s.uw a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = zext i32 %b to i64
  %2 = getelementptr i16, ptr %a, i64 %1
  %3 = load i16, ptr %2, align 2
  %4 = sext i16 %3 to i32
  ret i32 %4
}

define i32 @lxhu_s(ptr %a, iXLen %b) {
; RV32-LABEL: lxhu_s:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 1
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lhu a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxhu_s:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxhu.s a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxhu_s:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 1
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lhu a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxhu_s:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxhu.s a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = getelementptr i16, ptr %a, iXLen %b
  %2 = load i16, ptr %1, align 2
  %3 = zext i16 %2 to i32
  ret i32 %3
}

define i32 @lxhu_s_uw(ptr %a, i32 %b) {
; RV32-LABEL: lxhu_s_uw:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 1
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lhu a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxhu_s_uw:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxhu.s a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxhu_s_uw:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 31
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lhu a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxhu_s_uw:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxhu.s.uw a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = zext i32 %b to i64
  %2 = getelementptr i16, ptr %a, i64 %1
  %3 = load i16, ptr %2, align 2
  %4 = zext i16 %3 to i32
  ret i32 %4
}

define i32 @lxw_s_anyext(ptr %a, iXLen %b) {
; RV32-LABEL: lxw_s_anyext:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 2
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lw a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxw_s_anyext:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxw.s a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxw_s_anyext:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 2
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lw a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxw_s_anyext:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxw.s a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = getelementptr i32, ptr %a, iXLen %b
  %2 = load i32, ptr %1, align 4
  ret i32 %2
}

define i64 @lxw_s(ptr %a, iXLen %b) {
; RV32-LABEL: lxw_s:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 2
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lw a0, 0(a0)
; RV32-NEXT:    srai a1, a0, 31
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxw_s:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxw.s a0, (a0), a1
; RV32-ZILX-NEXT:    srai a1, a0, 31
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxw_s:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 2
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lw a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxw_s:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxw.s a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = getelementptr i32, ptr %a, iXLen %b
  %2 = load i32, ptr %1, align 4
  %3 = sext i32 %2 to i64
  ret i64 %3
}

define i32 @lxw_s_uw_anyext(ptr %a, i32 %b) {
; RV32-LABEL: lxw_s_uw_anyext:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 2
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lw a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxw_s_uw_anyext:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxw.s a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxw_s_uw_anyext:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 30
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lw a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxw_s_uw_anyext:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxw.s.uw a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = zext i32 %b to i64
  %2 = getelementptr i32, ptr %a, i64 %1
  %3 = load i32, ptr %2, align 4
  ret i32 %3
}

define i64 @lxw_s_uw(ptr %a, i32 %b) {
; RV32-LABEL: lxw_s_uw:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 2
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lw a0, 0(a0)
; RV32-NEXT:    srai a1, a0, 31
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxw_s_uw:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxw.s a0, (a0), a1
; RV32-ZILX-NEXT:    srai a1, a0, 31
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxw_s_uw:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 30
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lw a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxw_s_uw:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxw.s.uw a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = zext i32 %b to i64
  %2 = getelementptr i32, ptr %a, i64 %1
  %3 = load i32, ptr %2, align 4
  %4 = sext i32 %3 to i64
  ret i64 %4
}

define i64 @lxwu_s(ptr %a, iXLen %b) {
; RV32-LABEL: lxwu_s:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 2
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lw a0, 0(a0)
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxwu_s:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxw.s a0, (a0), a1
; RV32-ZILX-NEXT:    li a1, 0
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxwu_s:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 2
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lwu a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxwu_s:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxwu.s a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = getelementptr i32, ptr %a, iXLen %b
  %2 = load i32, ptr %1, align 4
  %3 = zext i32 %2 to i64
  ret i64 %3
}

define i64 @lxwu_s_uw(ptr %a, i32 %b) {
; RV32-LABEL: lxwu_s_uw:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 2
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lw a0, 0(a0)
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxwu_s_uw:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    lxw.s a0, (a0), a1
; RV32-ZILX-NEXT:    li a1, 0
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxwu_s_uw:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 30
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lwu a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxwu_s_uw:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxwu.s.uw a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = zext i32 %b to i64
  %2 = getelementptr i32, ptr %a, i64 %1
  %3 = load i32, ptr %2, align 4
  %4 = zext i32 %3 to i64
  ret i64 %4
}

define i64 @lxd_s(ptr %a, iXLen %b) {
; RV32-LABEL: lxd_s:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 3
; RV32-NEXT:    add a1, a0, a1
; RV32-NEXT:    lw a0, 0(a1)
; RV32-NEXT:    lw a1, 4(a1)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxd_s:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    slli a1, a1, 3
; RV32-ZILX-NEXT:    add a1, a0, a1
; RV32-ZILX-NEXT:    lw a0, 0(a1)
; RV32-ZILX-NEXT:    lw a1, 4(a1)
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxd_s:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 3
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    ld a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxd_s:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxd.s a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = getelementptr i64, ptr %a, iXLen %b
  %2 = load i64, ptr %1, align 8
  ret i64 %2
}

define i64 @lxd_s_2(ptr %a, iXLen %b) {
; RV32-LABEL: lxd_s_2:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 3
; RV32-NEXT:    add a1, a1, a0
; RV32-NEXT:    lw a0, 96(a1)
; RV32-NEXT:    lw a1, 100(a1)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxd_s_2:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    slli a1, a1, 3
; RV32-ZILX-NEXT:    add a1, a1, a0
; RV32-ZILX-NEXT:    lw a0, 96(a1)
; RV32-ZILX-NEXT:    lw a1, 100(a1)
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxd_s_2:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 3
; RV64-NEXT:    add a0, a1, a0
; RV64-NEXT:    ld a0, 96(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxd_s_2:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    addi a0, a0, 96
; RV64-ZILX-NEXT:    lxd.s a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = add iXLen %b, 12
  %2 = getelementptr i64, ptr %a, iXLen %1
  %3 = load i64, ptr %2, align 8
  ret i64 %3
}

define i64 @lxd_s_uw(ptr %a, i32 %b) {
; RV32-LABEL: lxd_s_uw:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 3
; RV32-NEXT:    add a1, a0, a1
; RV32-NEXT:    lw a0, 0(a1)
; RV32-NEXT:    lw a1, 4(a1)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxd_s_uw:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    slli a1, a1, 3
; RV32-ZILX-NEXT:    add a1, a0, a1
; RV32-ZILX-NEXT:    lw a0, 0(a1)
; RV32-ZILX-NEXT:    lw a1, 4(a1)
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxd_s_uw:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 29
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    ld a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxd_s_uw:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    lxd.s.uw a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = zext i32 %b to i64
  %2 = getelementptr i64, ptr %a, i64 %1
  %3 = load i64, ptr %2, align 8
  ret i64 %3
}

;------------------------------------------------------------------------------
; Load with a shift amount that doesn't match the access size
;
; The scaled forms require the index shift amount to match log2 of the access
; size. When the shift is smaller or larger than the access size the scaled
; forms can't be used: the shift is materialized separately, but the base+index
; add can still fold into the unscaled index load.
;------------------------------------------------------------------------------

; i8 access with the index scaled by 2 (larger than the access size).
define zeroext i8 @lxbu_shl_too_large(ptr %a, iXLen %b) {
; RV32-LABEL: lxbu_shl_too_large:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 2
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lbu a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxbu_shl_too_large:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    slli a1, a1, 2
; RV32-ZILX-NEXT:    lxbu a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxbu_shl_too_large:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 2
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lbu a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxbu_shl_too_large:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    slli a1, a1, 2
; RV64-ZILX-NEXT:    lxbu a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = getelementptr i32, ptr %a, iXLen %b
  %2 = load i8, ptr %1, align 1
  ret i8 %2
}

; i16 access with the index scaled by 2 (larger than the access size).
define signext i16 @lxh_s_shl_too_large(ptr %a, iXLen %b) {
; RV32-LABEL: lxh_s_shl_too_large:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 2
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lh a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxh_s_shl_too_large:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    slli a1, a1, 2
; RV32-ZILX-NEXT:    lxh a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxh_s_shl_too_large:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 2
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lh a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxh_s_shl_too_large:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    slli a1, a1, 2
; RV64-ZILX-NEXT:    lxh a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = getelementptr i32, ptr %a, iXLen %b
  %2 = load i16, ptr %1, align 2
  ret i16 %2
}

; i32 access with the index scaled by 1 (smaller than the access size).
define i32 @lxw_s_shl_too_small(ptr %a, iXLen %b) {
; RV32-LABEL: lxw_s_shl_too_small:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 1
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lw a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxw_s_shl_too_small:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    slli a1, a1, 1
; RV32-ZILX-NEXT:    lxw a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxw_s_shl_too_small:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 1
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lw a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxw_s_shl_too_small:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    slli a1, a1, 1
; RV64-ZILX-NEXT:    lxw a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = getelementptr i16, ptr %a, iXLen %b
  %2 = load i32, ptr %1, align 4
  ret i32 %2
}

; i32 access with the index scaled by 3 (larger than the access size).
define i32 @lxw_s_shl_too_large(ptr %a, iXLen %b) {
; RV32-LABEL: lxw_s_shl_too_large:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 3
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lw a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxw_s_shl_too_large:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    slli a1, a1, 3
; RV32-ZILX-NEXT:    lxw a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxw_s_shl_too_large:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 3
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lw a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxw_s_shl_too_large:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    slli a1, a1, 3
; RV64-ZILX-NEXT:    lxw a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = getelementptr i64, ptr %a, iXLen %b
  %2 = load i32, ptr %1, align 4
  ret i32 %2
}

; i64 access with the index scaled by 2 (smaller than the access size).
define i64 @lxd_s_shl_too_small(ptr %a, iXLen %b) {
; RV32-LABEL: lxd_s_shl_too_small:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 2
; RV32-NEXT:    add a1, a0, a1
; RV32-NEXT:    lw a0, 0(a1)
; RV32-NEXT:    lw a1, 4(a1)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxd_s_shl_too_small:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    addi a2, a0, 4
; RV32-ZILX-NEXT:    lxw.s a0, (a0), a1
; RV32-ZILX-NEXT:    lxw.s a1, (a2), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxd_s_shl_too_small:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 2
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    ld a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxd_s_shl_too_small:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    slli a1, a1, 2
; RV64-ZILX-NEXT:    lxd a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = getelementptr i32, ptr %a, iXLen %b
  %2 = load i64, ptr %1, align 8
  ret i64 %2
}

; i16 access with the zero-extended index scaled by 2 (larger than the access
; size).
define signext i16 @lxh_s_uw_shl_too_large(ptr %a, i32 %b) {
; RV32-LABEL: lxh_s_uw_shl_too_large:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 2
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lh a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxh_s_uw_shl_too_large:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    slli a1, a1, 2
; RV32-ZILX-NEXT:    lxh a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxh_s_uw_shl_too_large:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 30
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lh a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxh_s_uw_shl_too_large:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    slli a1, a1, 32
; RV64-ZILX-NEXT:    srli a1, a1, 30
; RV64-ZILX-NEXT:    lxh a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = zext i32 %b to i64
  %2 = getelementptr i32, ptr %a, i64 %1
  %3 = load i16, ptr %2, align 2
  ret i16 %3
}

; i32 access with the zero-extended index scaled by 1 (smaller than the access
; size).
define i32 @lxw_s_uw_shl_too_small(ptr %a, i32 %b) {
; RV32-LABEL: lxw_s_uw_shl_too_small:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 1
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lw a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxw_s_uw_shl_too_small:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    slli a1, a1, 1
; RV32-ZILX-NEXT:    lxw a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxw_s_uw_shl_too_small:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 31
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lw a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxw_s_uw_shl_too_small:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    slli a1, a1, 32
; RV64-ZILX-NEXT:    srli a1, a1, 31
; RV64-ZILX-NEXT:    lxw a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = zext i32 %b to i64
  %2 = getelementptr i16, ptr %a, i64 %1
  %3 = load i32, ptr %2, align 4
  ret i32 %3
}

; i32 access with the zero-extended index scaled by 3 (larger than the access
; size).
define i32 @lxw_s_uw_shl_too_large(ptr %a, i32 %b) {
; RV32-LABEL: lxw_s_uw_shl_too_large:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 3
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lw a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILX-LABEL: lxw_s_uw_shl_too_large:
; RV32-ZILX:       # %bb.0:
; RV32-ZILX-NEXT:    slli a1, a1, 3
; RV32-ZILX-NEXT:    lxw a0, (a0), a1
; RV32-ZILX-NEXT:    ret
;
; RV64-LABEL: lxw_s_uw_shl_too_large:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 29
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lw a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILX-LABEL: lxw_s_uw_shl_too_large:
; RV64-ZILX:       # %bb.0:
; RV64-ZILX-NEXT:    slli a1, a1, 32
; RV64-ZILX-NEXT:    srli a1, a1, 29
; RV64-ZILX-NEXT:    lxw a0, (a0), a1
; RV64-ZILX-NEXT:    ret
  %1 = zext i32 %b to i64
  %2 = getelementptr i64, ptr %a, i64 %1
  %3 = load i32, ptr %2, align 4
  ret i32 %3
}
