; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=aarch64 | FileCheck %s

; Test that bitcast(freeze(load)) is optimized to freeze(load) with appropriate type
define i32 @freeze_bitcast_load(ptr %p) {
; CHECK-LABEL: freeze_bitcast_load:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldr w8, [x0]
; CHECK-NEXT:    lsr w0, w8, #8
; CHECK-NEXT:    ret
  %load = load <4 x i8>, ptr %p, align 4
  %freeze = freeze <4 x i8> %load
  %bitcast = bitcast <4 x i8> %freeze to i32
  %result = lshr i32 %bitcast, 8
  ret i32 %result
}
