; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -verify-machineinstrs -mtriple=aarch64-apple-darwin < %s | FileCheck %s --implicit-check-not=.loh --check-prefixes=CHECK,LOH
; RUN: llc -verify-machineinstrs -mtriple=aarch64-apple-darwin -enable-machine-outliner < %s | FileCheck %s --implicit-check-not=.loh --check-prefixes=CHECK,OUTLINE

@A = global i32 0, align 4
@B = global i32 0, align 4

declare void @foo();
declare void @bar(ptr %a);
declare void @goo(ptr %a);

; CHECK-LABEL: _a0:
define void @a0(i32 %a) {

  ; This becomes AdrpAdd when outlining is disabled, otherwise it is outlined
  ; and there should be no LOH.
  %addr = getelementptr inbounds i32, ptr @A, i32 0
  %res = load i32, ptr %addr, align 4
  ; LOH:      [[L0:Lloh.+]]:
  ; LOH-NEXT:   adrp x8, _A@PAGE
  ; LOH-NEXT: [[L1:Lloh.+]]:
  ; LOH-NEXT:   add x8, x8, _A@PAGEOFF
  ; LOH-NEXT: [[L2:Lloh.+]]:
  ; LOH-NEXT:   ldr w19, [x8]

  call void @foo()
  ; OUTLINE:      bl _OUTLINED_FUNCTION_0
  
  ; CHECK:      [[L3:Lloh.+]]:
  ; CHECK-NEXT:   adrp x0, _A@PAGE
  ; CHECK-NEXT: [[L4:Lloh.+]]:
  ; CHECK-NEXT:   add x0, x0, _A@PAGEOFF
  ; CHECK-NEXT: bl _bar
  call void @bar(ptr %addr)

  ; This becomes AdrpAddStr.
  %addr2 = getelementptr inbounds i32, ptr @B, i32 4
  store i32 %res, ptr %addr2, align 4
  ; CHECK:      [[L5:Lloh.+]]:
  ; CHECK-NEXT:   adrp x8, _B@PAGE
  ; CHECK-NEXT: [[L6:Lloh.+]]:
  ; CHECK-NEXT:   add x8, x8, _B@PAGEOFF
  ; CHECK-NEXT: [[L7:Lloh.+]]:
  ; CHECK-NEXT:   str w19, [x8, #16]
  ret void

  ; LOH-DAG:   .loh AdrpAddLdr [[L0]], [[L1]], [[L2]]
  ; CHECK-DAG: .loh AdrpAdd [[L3]], [[L4]]
  ; CHECK-DAG: .loh AdrpAddStr [[L5]], [[L6]], [[L7]]
  ; CHECK:     .cfi_endproc
}

; CHECK-LABEL: _a1:
define i32 @a1(i32 %a) {

  ; This becomes AdrpAdd when outlining is disabled, otherwise it is outlined
  ; and there should be no LOH.
  %addr = getelementptr inbounds i32, ptr @A, i32 0
  %res = load i32, ptr %addr, align 4
  ; LOH:      [[L5:Lloh.+]]:
  ; LOH-NEXT:   adrp x8, _A@PAGE
  ; LOH-NEXT: [[L6:Lloh.+]]:
  ; LOH-NEXT:   add x8, x8, _A@PAGEOFF
  ; LOH-NEXT: [[L7:Lloh.+]]:
  ; LOH-NEXT:   ldr w19, [x8]

  call void @foo()
  ; OUTLINE:      bl _OUTLINED_FUNCTION_0

  ; CHECK:      [[L8:Lloh.+]]:
  ; CHECK-NEXT:   adrp x0, _A@PAGE
  ; CHECK-NEXT: [[L9:Lloh.+]]:
  ; CHECK-NEXT:   add x0, x0, _A@PAGEOFF
  ; CHECK-NEXT: bl _goo
  call void @goo(ptr %addr)
  ret i32 %res

  ; LOH-DAG: .loh AdrpAddLdr [[L5]], [[L6]], [[L7]]
  ; CHECK-DAG: .loh AdrpAdd [[L8]], [[L9]]
  ; CHECK: .cfi_endproc
}

; Note: it is not safe to add LOHs to this function as outlined functions do not
; follow calling convention and thus x8 could be live across the call.
; OUTLINE: _OUTLINED_FUNCTION_0:
; OUTLINE:   adrp x8, _A@PAGE
; OUTLINE:   add x8, x8, _A@PAGEOFF
; OUTLINE:   ldr w19, [x8]
; OUTLINE:   b _foo
