; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define i32 @test(i1 %C, i32 %tmp.15) {
; CHECK-LABEL: define i32 @test(
; CHECK-SAME: i1 [[C:%.*]], i32 [[TMP_15:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[C]], i32 3, i32 0, !prof [[PROF0:![0-9]+]]
; CHECK-NEXT:    [[TMP_181:%.*]] = lshr i32 [[TMP_15]], [[TMP1]]
; CHECK-NEXT:    ret i32 [[TMP_181]]
;
  %tmp.16 = select i1 %C, i32 8, i32 1, !prof !0           ; <i32> [#uses=1]
  %tmp.18 = udiv i32 %tmp.15, %tmp.16             ; <i32> [#uses=1]
  ret i32 %tmp.18
}

!0 = !{!"branch_weights", i32 10, i32 20}
;.
; CHECK: [[PROF0]] = !{!"branch_weights", i32 10, i32 20}
;.
