; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; Test folding of shuffle(phi(shuffle, ...), phi(shuffle, ...)) patterns
; where the inner shuffles have the same masks and the composition is identity.

; Identity on src0 (X): outer shuffle recovers X from interleaved shuffles
define <4 x i8> @identity_src0(<4 x i8> %x_then, <4 x i8> %y_then, <4 x i8> %x_else, <4 x i8> %y_else, i1 %cond) {
; CHECK-LABEL: @identity_src0(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[THEN:%.*]], label [[ELSE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    br label [[MERGE:%.*]]
; CHECK:       else:
; CHECK-NEXT:    br label [[MERGE]]
; CHECK:       merge:
; CHECK-NEXT:    [[SHUFFLE_PHI_OPT:%.*]] = phi <4 x i8> [ [[X_THEN:%.*]], [[THEN]] ], [ [[X_ELSE:%.*]], [[ELSE]] ]
; CHECK-NEXT:    ret <4 x i8> [[SHUFFLE_PHI_OPT]]
;
entry:
  br i1 %cond, label %then, label %else

then:
  ; Interleave low bytes: X[0], Y[0], X[1], Y[1]
  %inner0_then = shufflevector <4 x i8> %x_then, <4 x i8> %y_then, <4 x i32> <i32 0, i32 4, i32 1, i32 5>
  ; Interleave high bytes: X[2], Y[2], X[3], Y[3]
  %inner1_then = shufflevector <4 x i8> %x_then, <4 x i8> %y_then, <4 x i32> <i32 2, i32 6, i32 3, i32 7>
  br label %merge

else:
  %inner0_else = shufflevector <4 x i8> %x_else, <4 x i8> %y_else, <4 x i32> <i32 0, i32 4, i32 1, i32 5>
  %inner1_else = shufflevector <4 x i8> %x_else, <4 x i8> %y_else, <4 x i32> <i32 2, i32 6, i32 3, i32 7>
  br label %merge

merge:
  %phi0 = phi <4 x i8> [ %inner0_then, %then ], [ %inner0_else, %else ]
  %phi1 = phi <4 x i8> [ %inner1_then, %then ], [ %inner1_else, %else ]
  ; De-interleave to recover X: inner0[0], inner0[2], inner1[0], inner1[2]
  ;                            = X[0], X[1], X[2], X[3]
  %result = shufflevector <4 x i8> %phi0, <4 x i8> %phi1, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  ret <4 x i8> %result
}

; Identity on src1 (Y): outer shuffle recovers Y from interleaved shuffles
define <4 x i8> @identity_src1(<4 x i8> %x_then, <4 x i8> %y_then, <4 x i8> %x_else, <4 x i8> %y_else, i1 %cond) {
; CHECK-LABEL: @identity_src1(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[THEN:%.*]], label [[ELSE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    br label [[MERGE:%.*]]
; CHECK:       else:
; CHECK-NEXT:    br label [[MERGE]]
; CHECK:       merge:
; CHECK-NEXT:    [[SHUFFLE_PHI_OPT:%.*]] = phi <4 x i8> [ [[Y_THEN:%.*]], [[THEN]] ], [ [[Y_ELSE:%.*]], [[ELSE]] ]
; CHECK-NEXT:    ret <4 x i8> [[SHUFFLE_PHI_OPT]]
;
entry:
  br i1 %cond, label %then, label %else

then:
  %inner0_then = shufflevector <4 x i8> %x_then, <4 x i8> %y_then, <4 x i32> <i32 0, i32 4, i32 1, i32 5>
  %inner1_then = shufflevector <4 x i8> %x_then, <4 x i8> %y_then, <4 x i32> <i32 2, i32 6, i32 3, i32 7>
  br label %merge

else:
  %inner0_else = shufflevector <4 x i8> %x_else, <4 x i8> %y_else, <4 x i32> <i32 0, i32 4, i32 1, i32 5>
  %inner1_else = shufflevector <4 x i8> %x_else, <4 x i8> %y_else, <4 x i32> <i32 2, i32 6, i32 3, i32 7>
  br label %merge

merge:
  %phi0 = phi <4 x i8> [ %inner0_then, %then ], [ %inner0_else, %else ]
  %phi1 = phi <4 x i8> [ %inner1_then, %then ], [ %inner1_else, %else ]
  ; De-interleave to recover Y: inner0[1], inner0[3], inner1[1], inner1[3]
  ;                            = Y[0], Y[1], Y[2], Y[3]
  %result = shufflevector <4 x i8> %phi0, <4 x i8> %phi1, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  ret <4 x i8> %result
}

; Real pattern from MXFP4 GEMM kernel
define <4 x i8> @real_pattern(<4 x i8> %x_then, <4 x i8> %y_then, <4 x i8> %x_else, <4 x i8> %y_else, i1 %cond) {
; CHECK-LABEL: @real_pattern(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[THEN:%.*]], label [[ELSE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    br label [[MERGE:%.*]]
; CHECK:       else:
; CHECK-NEXT:    br label [[MERGE]]
; CHECK:       merge:
; CHECK-NEXT:    [[SHUFFLE_PHI_OPT:%.*]] = phi <4 x i8> [ [[X_THEN:%.*]], [[THEN]] ], [ [[X_ELSE:%.*]], [[ELSE]] ]
; CHECK-NEXT:    ret <4 x i8> [[SHUFFLE_PHI_OPT]]
;
entry:
  br i1 %cond, label %then, label %else

then:
  ; Interleave low halves: X[0], X[1], Y[0], Y[1]
  %inner0_then = shufflevector <4 x i8> %x_then, <4 x i8> %y_then, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  ; Interleave high halves: X[2], X[3], Y[2], Y[3]
  %inner1_then = shufflevector <4 x i8> %x_then, <4 x i8> %y_then, <4 x i32> <i32 2, i32 3, i32 6, i32 7>
  br label %merge

else:
  %inner0_else = shufflevector <4 x i8> %x_else, <4 x i8> %y_else, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  %inner1_else = shufflevector <4 x i8> %x_else, <4 x i8> %y_else, <4 x i32> <i32 2, i32 3, i32 6, i32 7>
  br label %merge

merge:
  %phi0 = phi <4 x i8> [ %inner0_then, %then ], [ %inner0_else, %else ]
  %phi1 = phi <4 x i8> [ %inner1_then, %then ], [ %inner1_else, %else ]
  ; Recover X: inner0[0], inner0[1], inner1[0], inner1[1]
  ;          = X[0], X[1], X[2], X[3]
  %result = shufflevector <4 x i8> %phi0, <4 x i8> %phi1, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  ret <4 x i8> %result
}

; Loop case: inner shuffles in loop backedge
define <4 x i8> @loop_backedge(<4 x i8> %x_init, <4 x i8> %y_init, <4 x i8> %x_update, <4 x i8> %y_update, i1 %cond) {
; CHECK-LABEL: @loop_backedge(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[SHUFFLE_PHI_OPT:%.*]] = phi <4 x i8> [ [[X_INIT:%.*]], [[ENTRY:%.*]] ], [ [[X_UPDATE:%.*]], [[LOOP]] ]
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[LOOP]], label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret <4 x i8> [[SHUFFLE_PHI_OPT]]
;
entry:
  %inner0_init = shufflevector <4 x i8> %x_init, <4 x i8> %y_init, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  %inner1_init = shufflevector <4 x i8> %x_init, <4 x i8> %y_init, <4 x i32> <i32 2, i32 3, i32 6, i32 7>
  br label %loop

loop:
  %phi0 = phi <4 x i8> [ %inner0_init, %entry ], [ %inner0_update, %loop ]
  %phi1 = phi <4 x i8> [ %inner1_init, %entry ], [ %inner1_update, %loop ]
  %result = shufflevector <4 x i8> %phi0, <4 x i8> %phi1, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  %inner0_update = shufflevector <4 x i8> %x_update, <4 x i8> %y_update, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  %inner1_update = shufflevector <4 x i8> %x_update, <4 x i8> %y_update, <4 x i32> <i32 2, i32 3, i32 6, i32 7>
  br i1 %cond, label %loop, label %exit

exit:
  ret <4 x i8> %result
}

; Negative test: different masks in different predecessors
define <4 x i8> @negative_different_masks(<4 x i8> %x_then, <4 x i8> %y_then, <4 x i8> %x_else, <4 x i8> %y_else, i1 %cond) {
; CHECK-LABEL: @negative_different_masks(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[THEN:%.*]], label [[ELSE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    [[INNER0_THEN:%.*]] = shufflevector <4 x i8> [[X_THEN:%.*]], <4 x i8> [[Y_THEN:%.*]], <4 x i32> <i32 0, i32 1, i32 4, i32 5>
; CHECK-NEXT:    [[INNER1_THEN:%.*]] = shufflevector <4 x i8> [[X_THEN]], <4 x i8> [[Y_THEN]], <4 x i32> <i32 2, i32 3, i32 6, i32 7>
; CHECK-NEXT:    br label [[MERGE:%.*]]
; CHECK:       else:
; CHECK-NEXT:    [[INNER0_ELSE:%.*]] = shufflevector <4 x i8> [[X_ELSE:%.*]], <4 x i8> [[Y_ELSE:%.*]], <4 x i32> <i32 1, i32 2, i32 5, i32 6>
; CHECK-NEXT:    [[INNER1_ELSE:%.*]] = shufflevector <4 x i8> [[X_ELSE]], <4 x i8> [[Y_ELSE]], <4 x i32> <i32 0, i32 3, i32 4, i32 7>
; CHECK-NEXT:    br label [[MERGE]]
; CHECK:       merge:
; CHECK-NEXT:    [[PHI0:%.*]] = phi <4 x i8> [ [[INNER0_THEN]], [[THEN]] ], [ [[INNER0_ELSE]], [[ELSE]] ]
; CHECK-NEXT:    [[PHI1:%.*]] = phi <4 x i8> [ [[INNER1_THEN]], [[THEN]] ], [ [[INNER1_ELSE]], [[ELSE]] ]
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <4 x i8> [[PHI0]], <4 x i8> [[PHI1]], <4 x i32> <i32 0, i32 1, i32 4, i32 5>
; CHECK-NEXT:    ret <4 x i8> [[RESULT]]
;
entry:
  br i1 %cond, label %then, label %else

then:
  %inner0_then = shufflevector <4 x i8> %x_then, <4 x i8> %y_then, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  %inner1_then = shufflevector <4 x i8> %x_then, <4 x i8> %y_then, <4 x i32> <i32 2, i32 3, i32 6, i32 7>
  br label %merge

else:
  ; Different masks!
  %inner0_else = shufflevector <4 x i8> %x_else, <4 x i8> %y_else, <4 x i32> <i32 1, i32 2, i32 5, i32 6>
  %inner1_else = shufflevector <4 x i8> %x_else, <4 x i8> %y_else, <4 x i32> <i32 0, i32 3, i32 4, i32 7>
  br label %merge

merge:
  %phi0 = phi <4 x i8> [ %inner0_then, %then ], [ %inner0_else, %else ]
  %phi1 = phi <4 x i8> [ %inner1_then, %then ], [ %inner1_else, %else ]
  %result = shufflevector <4 x i8> %phi0, <4 x i8> %phi1, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  ret <4 x i8> %result
}

; Negative test: PHI incoming value is not a shuffle
define <4 x i8> @negative_not_shuffle(<4 x i8> %x_then, <4 x i8> %y_then, <4 x i8> %x_else, <4 x i8> %y_else, i1 %cond) {
; CHECK-LABEL: @negative_not_shuffle(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[THEN:%.*]], label [[ELSE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    [[INNER1_THEN:%.*]] = shufflevector <4 x i8> [[X_THEN:%.*]], <4 x i8> [[Y_THEN:%.*]], <4 x i32> <i32 2, i32 3, i32 6, i32 7>
; CHECK-NEXT:    br label [[MERGE:%.*]]
; CHECK:       else:
; CHECK-NEXT:    [[INNER1_ELSE:%.*]] = shufflevector <4 x i8> [[X_ELSE:%.*]], <4 x i8> [[Y_ELSE:%.*]], <4 x i32> <i32 2, i32 3, i32 6, i32 7>
; CHECK-NEXT:    br label [[MERGE]]
; CHECK:       merge:
; CHECK-NEXT:    [[PHI0:%.*]] = phi <4 x i8> [ [[X_THEN]], [[THEN]] ], [ [[X_ELSE]], [[ELSE]] ]
; CHECK-NEXT:    [[PHI1:%.*]] = phi <4 x i8> [ [[INNER1_THEN]], [[THEN]] ], [ [[INNER1_ELSE]], [[ELSE]] ]
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <4 x i8> [[PHI0]], <4 x i8> [[PHI1]], <4 x i32> <i32 0, i32 1, i32 4, i32 5>
; CHECK-NEXT:    ret <4 x i8> [[RESULT]]
;
entry:
  br i1 %cond, label %then, label %else

then:
  ; First PHI input is the original value, not a shuffle
  %inner1_then = shufflevector <4 x i8> %x_then, <4 x i8> %y_then, <4 x i32> <i32 2, i32 3, i32 6, i32 7>
  br label %merge

else:
  %inner1_else = shufflevector <4 x i8> %x_else, <4 x i8> %y_else, <4 x i32> <i32 2, i32 3, i32 6, i32 7>
  br label %merge

merge:
  %phi0 = phi <4 x i8> [ %x_then, %then ], [ %x_else, %else ]
  %phi1 = phi <4 x i8> [ %inner1_then, %then ], [ %inner1_else, %else ]
  %result = shufflevector <4 x i8> %phi0, <4 x i8> %phi1, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  ret <4 x i8> %result
}

; Negative test: only one operand is a PHI
define <4 x i8> @negative_one_phi(<4 x i8> %x_then, <4 x i8> %y_then, <4 x i8> %x_else, <4 x i8> %y_else, <4 x i8> %z, i1 %cond) {
; CHECK-LABEL: @negative_one_phi(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[THEN:%.*]], label [[ELSE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    [[INNER0_THEN:%.*]] = shufflevector <4 x i8> [[X_THEN:%.*]], <4 x i8> [[Y_THEN:%.*]], <4 x i32> <i32 0, i32 1, i32 4, i32 5>
; CHECK-NEXT:    br label [[MERGE:%.*]]
; CHECK:       else:
; CHECK-NEXT:    [[INNER0_ELSE:%.*]] = shufflevector <4 x i8> [[X_ELSE:%.*]], <4 x i8> [[Y_ELSE:%.*]], <4 x i32> <i32 0, i32 1, i32 4, i32 5>
; CHECK-NEXT:    br label [[MERGE]]
; CHECK:       merge:
; CHECK-NEXT:    [[PHI0:%.*]] = phi <4 x i8> [ [[INNER0_THEN]], [[THEN]] ], [ [[INNER0_ELSE]], [[ELSE]] ]
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <4 x i8> [[PHI0]], <4 x i8> [[Z:%.*]], <4 x i32> <i32 0, i32 1, i32 4, i32 5>
; CHECK-NEXT:    ret <4 x i8> [[RESULT]]
;
entry:
  br i1 %cond, label %then, label %else

then:
  %inner0_then = shufflevector <4 x i8> %x_then, <4 x i8> %y_then, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  br label %merge

else:
  %inner0_else = shufflevector <4 x i8> %x_else, <4 x i8> %y_else, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  br label %merge

merge:
  %phi0 = phi <4 x i8> [ %inner0_then, %then ], [ %inner0_else, %else ]
  ; Second operand is not a PHI
  %result = shufflevector <4 x i8> %phi0, <4 x i8> %z, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  ret <4 x i8> %result
}

; Negative test: non-identity composition
define <4 x i8> @negative_non_identity(<4 x i8> %x_then, <4 x i8> %y_then, <4 x i8> %x_else, <4 x i8> %y_else, i1 %cond) {
; CHECK-LABEL: @negative_non_identity(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[THEN:%.*]], label [[ELSE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    [[INNER0_THEN:%.*]] = shufflevector <4 x i8> [[X_THEN:%.*]], <4 x i8> [[Y_THEN:%.*]], <4 x i32> <i32 0, i32 1, i32 4, i32 5>
; CHECK-NEXT:    [[INNER1_THEN:%.*]] = shufflevector <4 x i8> [[X_THEN]], <4 x i8> [[Y_THEN]], <4 x i32> <i32 2, i32 3, i32 6, i32 7>
; CHECK-NEXT:    br label [[MERGE:%.*]]
; CHECK:       else:
; CHECK-NEXT:    [[INNER0_ELSE:%.*]] = shufflevector <4 x i8> [[X_ELSE:%.*]], <4 x i8> [[Y_ELSE:%.*]], <4 x i32> <i32 0, i32 1, i32 4, i32 5>
; CHECK-NEXT:    [[INNER1_ELSE:%.*]] = shufflevector <4 x i8> [[X_ELSE]], <4 x i8> [[Y_ELSE]], <4 x i32> <i32 2, i32 3, i32 6, i32 7>
; CHECK-NEXT:    br label [[MERGE]]
; CHECK:       merge:
; CHECK-NEXT:    [[PHI0:%.*]] = phi <4 x i8> [ [[INNER0_THEN]], [[THEN]] ], [ [[INNER0_ELSE]], [[ELSE]] ]
; CHECK-NEXT:    [[PHI1:%.*]] = phi <4 x i8> [ [[INNER1_THEN]], [[THEN]] ], [ [[INNER1_ELSE]], [[ELSE]] ]
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <4 x i8> [[PHI0]], <4 x i8> [[PHI1]], <4 x i32> <i32 1, i32 0, i32 5, i32 4>
; CHECK-NEXT:    ret <4 x i8> [[RESULT]]
;
entry:
  br i1 %cond, label %then, label %else

then:
  %inner0_then = shufflevector <4 x i8> %x_then, <4 x i8> %y_then, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  %inner1_then = shufflevector <4 x i8> %x_then, <4 x i8> %y_then, <4 x i32> <i32 2, i32 3, i32 6, i32 7>
  br label %merge

else:
  %inner0_else = shufflevector <4 x i8> %x_else, <4 x i8> %y_else, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  %inner1_else = shufflevector <4 x i8> %x_else, <4 x i8> %y_else, <4 x i32> <i32 2, i32 3, i32 6, i32 7>
  br label %merge

merge:
  %phi0 = phi <4 x i8> [ %inner0_then, %then ], [ %inner0_else, %else ]
  %phi1 = phi <4 x i8> [ %inner1_then, %then ], [ %inner1_else, %else ]
  ; Non-identity: swaps within pairs
  %result = shufflevector <4 x i8> %phi0, <4 x i8> %phi1, <4 x i32> <i32 1, i32 0, i32 5, i32 4>
  ret <4 x i8> %result
}

; Multi-use case: inner shuffles used elsewhere, should still optimize
; The unused inner1 shuffles will be DCE'd since they're no longer used after optimization
define <4 x i8> @multi_use(<4 x i8> %x_then, <4 x i8> %y_then, <4 x i8> %x_else, <4 x i8> %y_else, i1 %cond, ptr %out) {
; CHECK-LABEL: @multi_use(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[THEN:%.*]], label [[ELSE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    [[INNER0_THEN:%.*]] = shufflevector <4 x i8> [[X_THEN:%.*]], <4 x i8> [[Y_THEN:%.*]], <4 x i32> <i32 0, i32 1, i32 4, i32 5>
; CHECK-NEXT:    br label [[MERGE:%.*]]
; CHECK:       else:
; CHECK-NEXT:    [[INNER0_ELSE:%.*]] = shufflevector <4 x i8> [[X_ELSE:%.*]], <4 x i8> [[Y_ELSE:%.*]], <4 x i32> <i32 0, i32 1, i32 4, i32 5>
; CHECK-NEXT:    br label [[MERGE]]
; CHECK:       merge:
; CHECK-NEXT:    [[SHUFFLE_PHI_OPT:%.*]] = phi <4 x i8> [ [[X_THEN]], [[THEN]] ], [ [[X_ELSE]], [[ELSE]] ]
; CHECK-NEXT:    [[PHI0:%.*]] = phi <4 x i8> [ [[INNER0_THEN]], [[THEN]] ], [ [[INNER0_ELSE]], [[ELSE]] ]
; CHECK-NEXT:    store <4 x i8> [[PHI0]], ptr [[OUT:%.*]], align 4
; CHECK-NEXT:    ret <4 x i8> [[SHUFFLE_PHI_OPT]]
;
entry:
  br i1 %cond, label %then, label %else

then:
  %inner0_then = shufflevector <4 x i8> %x_then, <4 x i8> %y_then, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  %inner1_then = shufflevector <4 x i8> %x_then, <4 x i8> %y_then, <4 x i32> <i32 2, i32 3, i32 6, i32 7>
  br label %merge

else:
  %inner0_else = shufflevector <4 x i8> %x_else, <4 x i8> %y_else, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  %inner1_else = shufflevector <4 x i8> %x_else, <4 x i8> %y_else, <4 x i32> <i32 2, i32 3, i32 6, i32 7>
  br label %merge

merge:
  %phi0 = phi <4 x i8> [ %inner0_then, %then ], [ %inner0_else, %else ]
  %phi1 = phi <4 x i8> [ %inner1_then, %then ], [ %inner1_else, %else ]
  ; phi0 is also used here
  store <4 x i8> %phi0, ptr %out
  %result = shufflevector <4 x i8> %phi0, <4 x i8> %phi1, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  ret <4 x i8> %result
}
