; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes="loop-reduce" -S | FileCheck %s

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @regression1() {
; CHECK-LABEL: define void @regression1() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[LOOP1_HEADER:.*]]
; CHECK:       [[LOOP1_HEADER]]:
; CHECK-NEXT:    br label %[[LOOP1:.*]]
; CHECK:       [[LOOP1]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i32 [ 0, %[[LOOP1_HEADER]] ], [ 1, %[[LOOP1]] ]
; CHECK-NEXT:    br i1 false, label %[[LOOP2_HEADER:.*]], label %[[LOOP1]]
; CHECK:       [[LOOP2_HEADER]]:
; CHECK-NEXT:    [[PHI_LCSSA1:%.*]] = phi i32 [ [[PHI]], %[[LOOP1]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = add nuw nsw i32 [[PHI_LCSSA1]], 1
; CHECK-NEXT:    br label %[[LOOP2:.*]]
; CHECK:       [[LOOP2]]:
; CHECK-NEXT:    [[LSR_IV:%.*]] = phi i32 [ [[LSR_IV_NEXT:%.*]], %[[LOOP2]] ], [ [[TMP0]], %[[LOOP2_HEADER]] ]
; CHECK-NEXT:    [[SELECT:%.*]] = select i1 false, i32 [[LSR_IV]], i32 0
; CHECK-NEXT:    [[LSR_IV_NEXT]] = add i32 [[LSR_IV]], 1
; CHECK-NEXT:    br i1 false, label %[[EXIT:.*]], label %[[LOOP2]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    br label %[[LOOP1_HEADER]]
;
entry:
  br label %loop1.header

loop1.header:                                              ; preds = %exit, %entry
  br label %loop1

loop1:                                              ; preds = %loop1, %loop1.header
  %phi = phi i32 [ 0, %loop1.header ], [ 1, %loop1 ]
  br i1 false, label %loop2.header, label %loop1

loop2.header:                                              ; preds = %loop1
  br label %loop2

loop2:                                              ; preds = %loop2.header, %loop2
  %phi5 = phi i32 [ %add, %loop2 ], [ %phi, %loop2.header ]
  %add = add i32 %phi5, 1
  %select = select i1 false, i32 %add, i32 0
  br i1 false, label %exit, label %loop2

exit:                                              ; preds = %loop2
  br label %loop1.header
}

define void @barney() {
; CHECK-LABEL: define void @barney() {
; CHECK-NEXT:  [[BB:.*:]]
; CHECK-NEXT:    br label %[[BB1:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    switch i8 0, label %[[BB1_BACKEDGE:.*]] [
; CHECK-NEXT:      i8 63, label %[[BB2_PREHEADER:.*]]
; CHECK-NEXT:      i8 43, label %[[BB2_PREHEADER]]
; CHECK-NEXT:      i8 42, label %[[BB2_PREHEADER]]
; CHECK-NEXT:    ]
; CHECK:       [[BB1_BACKEDGE]]:
; CHECK-NEXT:    br label %[[BB1]]
; CHECK:       [[BB2_PREHEADER]]:
; CHECK-NEXT:    br label %[[BB2:.*]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i32 [ [[ADD4:%.*]], %[[BB3:.*]] ], [ 0, %[[BB2_PREHEADER]] ]
; CHECK-NEXT:    br i1 false, label %[[BB3]], label %[[BB2_BB5_CRIT_EDGE:.*]]
; CHECK:       [[BB3]]:
; CHECK-NEXT:    [[ADD:%.*]] = add i32 0, 0
; CHECK-NEXT:    [[ADD4]] = add i32 [[PHI]], 1
; CHECK-NEXT:    br i1 false, label %[[BB2]], label %[[BB5SPLIT:.*]]
; CHECK:       [[BB5SPLIT]]:
; CHECK-NEXT:    [[ADD_LCSSA:%.*]] = phi i32 [ [[ADD]], %[[BB3]] ]
; CHECK-NEXT:    br label %[[BB5:.*]]
; CHECK:       [[BB2_BB5_CRIT_EDGE]]:
; CHECK-NEXT:    [[PHI_LCSSA:%.*]] = phi i32 [ [[PHI]], %[[BB2]] ]
; CHECK-NEXT:    br label %[[BB5]]
; CHECK:       [[BB5]]:
; CHECK-NEXT:    [[PHI6:%.*]] = phi i32 [ 0, %[[BB2_BB5_CRIT_EDGE]] ], [ [[ADD_LCSSA]], %[[BB5SPLIT]] ]
; CHECK-NEXT:    [[PHI7:%.*]] = phi i32 [ [[PHI_LCSSA]], %[[BB2_BB5_CRIT_EDGE]] ], [ 0, %[[BB5SPLIT]] ]
; CHECK-NEXT:    br label %[[BB1_BACKEDGE]]
;
bb:
  br label %bb1

bb1:                                              ; preds = %bb5, %bb1, %bb
  switch i8 0, label %bb1 [
  i8 63, label %bb2
  i8 43, label %bb2
  i8 42, label %bb2
  ]

bb2:                                              ; preds = %bb3, %bb1, %bb1, %bb1
  %phi = phi i32 [ %add4, %bb3 ], [ 0, %bb1 ], [ 0, %bb1 ], [ 0, %bb1 ]
  br i1 false, label %bb3, label %bb5

bb3:                                              ; preds = %bb2
  %add = add i32 0, 0
  %add4 = add i32 %phi, 1
  br i1 false, label %bb2, label %bb5

bb5:                                              ; preds = %bb3, %bb2
  %phi6 = phi i32 [ %add, %bb3 ], [ 0, %bb2 ]
  %phi7 = phi i32 [ 0, %bb3 ], [ %phi, %bb2 ]
  br label %bb1
}
