# ===- Hex numbers writer for wctype include files -----------*- python -*--==#
#
# Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# ==------------------------------------------------------------------------==#

import cppyy


def fetch_params(file_path: str, mappings: dict):
    file_path_list = file_path.split("/")[:-1]
    file_path_list.append("perfect_hash_map.h")

    cppyy.include("/".join(file_path_list))

    LIBC_NAMESPACE = cppyy.gbl.LIBC_NAMESPACE

    arr = LIBC_NAMESPACE.cpp.array[cppyy.gbl.wint_t, len(mappings)]()

    for i, key in enumerate(mappings.keys()):
        arr[i] = key

    res = LIBC_NAMESPACE.ptrhash.get_params(arr)
    pilots = LIBC_NAMESPACE.cpp.get[1](res)
    pilots_size = pilots.size()
    pilots = list(map(lambda x: f"0x{x:X}", map(cppyy.gbl.uint8_t, pilots)))
    pilots = ", ".join(pilots).replace("[", "{").replace("]", "}")
    pilots = "{" + pilots + "}"

    remap = LIBC_NAMESPACE.cpp.get[2](res)
    remap_size = remap.size()
    remap = map(lambda x: f"0x{x:X}", map(cppyy.gbl.uint32_t, remap))
    remap = list(remap)
    remap = ", ".join(remap).replace("[", "{").replace("]", "}")
    remap = "{" + remap + "}"
    return (
        f"0x{cppyy.gbl.uint8_t(LIBC_NAMESPACE.cpp.get[0](res)):X}",
        (pilots, pilots_size),
        (remap, remap_size),
    )


def write_hex_conversions(file_path: str, mappings: dict[int, int]) -> None:
    """Writes the given mapping as hex numbers to the given file path"""
    with open(file_path, "w") as file:
        title = file_path.split("/")[-1].split(".")[0].replace("_", " ")
        data_var_name = f"{title.upper().replace(' ', '_')}_DATA"
        file.write(
            f"""//===-- Auto-generated {title} case mappings table -------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
"""
            + "// DO NOT EDIT MANUALLY.\n"
            + "// This file is generated by libc/utils/wctype_utils scripts.\n"
            + "// This file is meant to be included directly into LLVM libc code\n"
            + "// Format: {from_codepoint, to_codepoint}\n"
            + f"// Info: {len(mappings)} entries\n"
        )
        file.write(
            f"""
#ifndef LLVM_LIBC_SRC___SUPPORT_WCTYPE_{data_var_name[:-5]}_H
#define LLVM_LIBC_SRC___SUPPORT_WCTYPE_{data_var_name[:-5]}_H

#include "perfect_hash_map.h"

namespace LIBC_NAMESPACE_DECL {'{'}

"""
            + f"LIBC_INLINE_VAR constexpr cpp::array<cpp::array<wint_t, 2>, {len(mappings)}>"
            + f"""
    {data_var_name} = """
        )
        file.write("{{\n")
        for i, key in enumerate(mappings):
            file.write("{")
            file.write(f"0x{key:X}, 0x{mappings[key]:X}")
            if i == len(mappings) - 1:
                file.write("}\n")
            else:
                file.write("},\n")
        file.write("}};\n\n")

        seed, (pilots, pilots_size), (remap, remap_size) = fetch_params(
            file_path, mappings
        )
        file.write(
            f"LIBC_INLINE_VAR constexpr auto {data_var_name[:-5]}_HASHER = ptrhash::init_hasher<{len(mappings)}>({seed}, cpp::array<uint8_t, {pilots_size}>{pilots}, cpp::array<uint32_t, {remap_size}>{remap});\n\n"
        )
        file.write(
            f"LIBC_INLINE_VAR constexpr PerfectHashMap<{len(mappings)}, decltype({data_var_name[:-5]}_HASHER)> "
            + data_var_name[:-5]
            + "_MAP"
            + "{\n"
        )
        file.write(f"{data_var_name}, {data_var_name[:-5]}_HASHER")
        file.write("};")

        file.write("\n\n} // namespace LIBC_NAMESPACE_DECL\n\n")
        file.write(
            f"#endif // LLVM_LIBC_SRC___SUPPORT_WCTYPE_{data_var_name[:-5]}_H\n")
