name: Check CI Scripts

permissions:
  contents: read

on:
  push:
    branches:
     - main
    paths:
     - '.ci/**'
     - '.github/workflows/check-ci.yml'
  pull_request:
    paths:
     - '.ci/**'
     - '.github/workflows/check-ci.yml'

jobs:
  test-python:
    name: "Check Python Tests"
    runs-on: ubuntu-24.04
    if: github.repository == 'llvm/llvm-project'
    steps:
      - name: Fetch LLVM sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: .ci
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.13
          cache: 'pip'
      - name: Install Python Dependencies
        run: |
          pip3 install -r .ci/all_requirements.txt
          pip3 install -r .ci/metrics/requirements.lock.txt
          pip3 install pytest==8.4.1
      - name: Run Tests
        working-directory: .ci
        run: pytest
